INPUT ("")
OUTPUT ("\
Project-Id-Version: GNU libc 2.1.3\n\
POT-Creation-Date: 2000-02-16 10:39-0800\n\
PO-Revision-Date: 2000-02-23 05:03+01:00\n\
Last-Translator: Jochen Hein <jochen@jochen.org>\n\
Language-Team: German <de@li.org>\n\
MIME-Version: 1.0\n\
Content-Type: text/plain; charset=ISO-8859-1\n\
Content-Transfer-Encoding: 8-bit\n")
INPUT ("\t\tAccess Rights : ")
OUTPUT ("\t\tZugriffsrechte : ")
INPUT ("\t\tAttributes    : ")
OUTPUT ("\t\tAttribute      : ")
INPUT ("\t%s [-abkCLNTM][-Dname[=value]] [-i size] [-I [-K seconds]] [-Y path] infile\n")
OUTPUT ("\t%s [-abkCLNTM][-DName[=Wert]] [-i Größe] [-I [-K Sekunden]] [-Y Pfad] Eingabedatei\n")
INPUT ("\t%s [-c | -h | -l | -m | -t | -Sc | -Ss | -Sm] [-o outfile] [infile]\n")
OUTPUT ("\t%s [-c | -h | -l | -m | -t | -Sc | -Ss | -Sm] [-o Ausgabedatei] [Eingabedatei]\n")
INPUT ("\t%s [-n netid]* [-o outfile] [infile]\n")
OUTPUT ("\t%s [-n Netz-ID]* [-o Ausgabedatei] [Eingabedatei]\n")
INPUT ("\t%s [-s nettype]* [-o outfile] [infile]\n")
OUTPUT ("\t%s [-s Netz-Typ]* [-o Ausgabedatei] [Eingabedatei]\n")
INPUT ("\tAccess rights: ")
OUTPUT ("\tZugriffsrechte : ")
INPUT ("\tEntry data of type %s\n")
OUTPUT ("\tDateneingabe vom Typ %s\n")
INPUT ("\tName       : %s\n")
OUTPUT ("\tName         : %s\n")
INPUT ("\tPublic Key : ")
OUTPUT ("\tPublic Key   : ")
INPUT ("\tType         : %s\n")
OUTPUT ("\tTyp            : %s\n")
INPUT ("\tUniversal addresses (%u)\n")
OUTPUT ("\tUniverselle Adressen (%u)\n")
INPUT ("\t[%d]\tName          : %s\n")
OUTPUT ("\t[%d]\tName          : %s\n")
INPUT ("\t[%u] - [%u bytes] ")
OUTPUT ("\t[%u] - [%u Bytes] ")
INPUT ("\
\n\
%s cache:\n\
\n\
%15s  cache is enabled\n\
%15Zd  suggested size\n\
%15ld  seconds time to live for positive entries\n\
%15ld  seconds time to live for negative entries\n\
%15ld  cache hits on positive entries\n\
%15ld  cache hits on negative entries\n\
%15ld  cache misses on positive entries\n\
%15ld  cache misses on negative entries\n\
%15ld%% cache hit rate\n\
%15s  check /etc/%s for changes\n")
OUTPUT ("\
\n\
%s Cache:\n\
\n\
%15s  Cache ist eingeschaltet\n\
%15Zd  vorgeschlagene Größe\n\
%15ld  Time to Live für positive Einträge in Sekunden\n\
%15ld  Time to Live für negative Einträge in Sekunden\n\
%15ld  Cache-Hits bei positiven Einträgen\n\
%15ld  Cache-Hits bei positiven Einträgen\n\
%15ld  Cache-Misses bei positiven Einträgen\n\
%15ld  Cache-Misses bei negativen Einträgen\n\
%15ld%% Cache-Hit Verhältnis\n\
%15s  Prüfe /etc/%s auf Änderungen\n")
INPUT ("\nGroup Members :\n")
OUTPUT ("\nGruppen Mitglieder :\n")
INPUT ("\nTime to Live  : ")
OUTPUT ("\nTime to Live        : ")
INPUT ("       rpcinfo -b prognum versnum\n")
OUTPUT ("       rpcinfo -b Programmnummer Versionsnummer\n")
INPUT ("       rpcinfo -d prognum versnum\n")
OUTPUT ("       rpcinfo -d Programmnummer Versionsnummer\n")
INPUT ("       rpcinfo -p [ host ]\n")
OUTPUT ("       rpcinfo -p [ Rechner ]\n")
INPUT ("       rpcinfo [ -n portnum ] -t host prognum [ versnum ]\n")
OUTPUT ("       rpcinfo [ -n Portnummer ] -t Rechner Programmnummer [ Versionsnummer ]\n")
INPUT ("      no")
OUTPUT ("      nein")
INPUT ("     yes")
OUTPUT ("     ja")
INPUT ("    Data Length = %u\n")
OUTPUT ("    Länge der Daten = %u\n")
INPUT ("    Explicit members:\n")
OUTPUT ("    Explizite Mitglieder:\n")
INPUT ("    Explicit nonmembers:\n")
OUTPUT ("    Explizite Nicht-Mitglieder:\n")
INPUT ("    Implicit members:\n")
OUTPUT ("    Implizite Mitglieder:\n")
INPUT ("    Implicit nonmembers:\n")
OUTPUT ("    Implizite Nicht-Mitglieder:\n")
INPUT ("    No explicit members\n")
OUTPUT ("    Keine expliziten Mitglieder\n")
INPUT ("    No explicit nonmembers\n")
OUTPUT ("    Keine expliziten Nicht-Mitglieder\n")
INPUT ("    No implicit members\n")
OUTPUT ("    Keine impliziten Mitglieder\n")
INPUT ("    No implicit nonmembers\n")
OUTPUT ("    Keine impliziten Nicht-Mitglieder\n")
INPUT ("    No recursive members\n")
OUTPUT ("    Keine rekursiven Mitglieder\n")
INPUT ("    No recursive nonmembers\n")
OUTPUT ("    Keine rekursiven Nicht-Mitglieder\n")
INPUT ("    Recursive members:\n")
OUTPUT ("    Rekursive Mitglieder:\n")
INPUT ("   program vers proto   port\n")
OUTPUT ("   Program Vers Proto   Port\n")
INPUT ("  or: ")
OUTPUT ("  oder: ")
INPUT (" (rule from \"%s\", line %d)")
OUTPUT (" (Regel aus Datei »%s«, Zeile %d)")
INPUT (" [OPTION...]")
OUTPUT (" [Option...]")
INPUT (" done\n")
OUTPUT (" fertig\n")
INPUT ("\"%s\", line %d: %s")
OUTPUT ("»%s«, Zeile %d: %s")
INPUT ("\"Zone %s\" line and -l option are mutually exclusive")
OUTPUT ("»Zone %s«-Zeile und die Option »-l« schliessen sich aus")
INPUT ("\"Zone %s\" line and -p option are mutually exclusive")
OUTPUT ("»Zone %s«-Zeile und die Option »-p« schliessen sich aus")
INPUT ("\"infile\" is required for template generation flags.\n")
OUTPUT ("»infile« ist für die Template-Generierungs-Flags erforderlich\n")
INPUT ("%.*s: ARGP_HELP_FMT parameter requires a value")
OUTPUT ("%.*s: ARGP_HELP_FMT Parameter verlangt einen Wert")
INPUT ("%.*s: Unknown ARGP_HELP_FMT parameter")
OUTPUT ("%.*s: Unbekannter ARGP_HELP_FMT Parameter")
INPUT ("%s in ruleless zone")
OUTPUT ("%s in einer regellosen Zone")
INPUT ("%s%s%s:%u: %s%sAssertion `%s' failed.\n")
OUTPUT ("%s%s%s:%u: %s%sZusicherung »%s« nicht erfüllt.\n")
INPUT ("%s%s%s:%u: %s%sUnexpected error: %s.\n")
OUTPUT ("%s%s%s:%u: %s%sNicht erwarteter Fehler: %s.\n")
INPUT ("%s%sUnknown signal %d\n")
OUTPUT ("%s%sUnbekanntes Signal %d\n")
INPUT ("%s: %d did not sign extend correctly\n")
OUTPUT ("%s: Vorzeichenerweiterung von %d fehlgeschlagen\n")
INPUT ("%s: <mb_cur_max> must be greater than <mb_cur_min>\n")
OUTPUT ("%s: »<mb_cur_max>« muß größer als »<mb_cur_min>« sein\n")
INPUT ("%s: C preprocessor failed with exit code %d\n")
OUTPUT ("%s: C Präprozessor fehlgeschlagen mit Exit-Code %d\n")
INPUT ("%s: C preprocessor failed with signal %d\n")
OUTPUT ("%s: C Präprozessor fehlgeschlagen mit Signal %d\n")
INPUT ("%s: Can't create %s: %s\n")
OUTPUT ("%s: Kann »%s« nicht erzeugen: %s\n")
INPUT ("%s: Can't create directory %s: %s\n")
OUTPUT ("%s: Kann das Verzeichnis »%s« nicht erzeugen: %s\n")
INPUT ("%s: Can't link from %s to %s: %s\n")
OUTPUT ("%s: Kann nicht von »%s« nach »%s« linken: %s\n")
INPUT ("%s: Can't open %s: %s\n")
OUTPUT ("%s: Kann die Datei »%s« nicht öffnen: %s\n")
INPUT ("%s: Can't remove %s: %s\n")
OUTPUT ("%s: Kann »%s« nicht löschen: %s\n")
INPUT ("%s: Can't unlink  %s: %s\n")
OUTPUT ("%s: Kann den Verzeichniseintrag »%s« nicht löschen (unlink): %s\n")
INPUT ("%s: Error closing %s: %s\n")
OUTPUT ("%s: Fehler beim Schließen der Datei »%s«: %s\n")
INPUT ("%s: Error reading %s\n")
OUTPUT ("%s: Fehler beim Lesen der Datei »%s«\n")
INPUT ("%s: Error writing ")
OUTPUT ("%s: Fehler beim Schreiben ")
INPUT ("%s: Error writing %s\n")
OUTPUT ("%s: Fehler beim Schreiben der Datei »%s«\n")
INPUT ("%s: Leap line in non leap seconds file %s\n")
OUTPUT ("%s: Schalt-Zeile in einer nicht-Schaltsekunden-Datei »%s«\n")
INPUT ("%s: Memory exhausted: %s\n")
OUTPUT ("%s: Kein Hauptspeicher mehr verfügbar: %s\n")
INPUT ("%s: More than one -L option specified\n")
OUTPUT ("%s: Mehr als eine »-L« Option angegeben\n")
INPUT ("%s: More than one -d option specified\n")
OUTPUT ("%s: Mehr als eine »-d« Option angegeben\n")
INPUT ("%s: More than one -l option specified\n")
OUTPUT ("%s: Mehr als eine »-l« Option angegeben\n")
INPUT ("%s: More than one -p option specified\n")
OUTPUT ("%s: Mehr als eine »-p« Option angegeben\n")
INPUT ("%s: More than one -y option specified\n")
OUTPUT ("%s: Mehr als eine »-y« Option angegeben\n")
INPUT ("%s: Too many arguments\n")
OUTPUT ("%s: Zu viele Argumente\n")
INPUT ("%s: cannot get modification time")
OUTPUT ("%s: kann die Modifikationszeit nicht bekommen")
INPUT ("%s: command was '%s', result was %d\n")
OUTPUT ("%s: Das Kommando war »%s«, das Ergebnis war %d\n")
INPUT ("%s: error in state machine")
OUTPUT ("%s: Fehler im (intern verwendeten) endlichen Automaten")
INPUT ("%s: illegal option -- %c\n")
OUTPUT ("%s: Die Option ist nicht erlaubt -- »%c«\n")
INPUT ("%s: invalid option -- %c\n")
OUTPUT ("%s: Ungültige Option -- »%c«\n")
INPUT ("%s: option `%c%s' doesn't allow an argument\n")
OUTPUT ("%s: Die Option »%c%s« erlaubt kein Argument\n")
INPUT ("%s: option `%s' is ambiguous\n")
OUTPUT ("%s: Die Option »%s« ist nicht eindeutig\n")
INPUT ("%s: option `%s' requires an argument\n")
OUTPUT ("%s: Die Option »%s« erfordert ein Argument\n")
INPUT ("%s: option `--%s' doesn't allow an argument\n")
OUTPUT ("%s: Die Option »--%s« erlaubt kein Argument\n")
INPUT ("%s: option `-W %s' doesn't allow an argument\n")
OUTPUT ("%s: Die Option »-W %s« erlaubt kein Argument\n")
INPUT ("%s: option `-W %s' is ambiguous\n")
OUTPUT ("%s: Die Option »-W %s« ist nicht eindeutig\n")
INPUT ("%s: option requires an argument -- %c\n")
OUTPUT ("%s: Diese Option benötigt ein Argument -- »%c«\n")
INPUT ("%s: output would overwrite %s\n")
OUTPUT ("%s: Die Ausgabe würde »%s« überschreiben\n")
INPUT ("%s: panic: Invalid l_value %d\n")
OUTPUT ("%s: Panik: ungültiger »l_value« %d\n")
INPUT ("%s: premature end of file")
OUTPUT ("%s: Unerwartetes Ende der Datei")
INPUT ("%s: unable to open %s: %m\n")
OUTPUT ("%s: Fehler beim Öffnen von »%s«: %m\n")
INPUT ("%s: unrecognized option `%c%s'\n")
OUTPUT ("%s: Unbekannte Option »%c%s«\n")
INPUT ("%s: unrecognized option `--%s'\n")
OUTPUT ("%s: Unbekannte Option »--%s«\n")
INPUT ("\
%s: usage is %s [ -s ] [ -v ] [ -l localtime ] [ -p posixrules ] [ -d directory ]\n\
\t[ -L leapseconds ] [ -y yearistype ] [ filename ... ]\n")
OUTPUT ("\
%s: Syntax ist %s [ -s ] [ -v ] [ -l Ortszeit ] [ -p Posix-Regeln ] [ -d Verzeichnis ]\n\
\t[ -L Schaltsekunden ] [ -y Jahrestyp ] [ Dateiname ... ]\n")
INPUT ("%s: usage is %s [ -v ] [ -c cutoff ] zonename ...\n")
OUTPUT ("%s: Syntax: %s [ -v ] [ -c cutoff ] Zonenname ...\n")
INPUT ("%s: while writing output %s: %m")
OUTPUT ("%s: Beim Schreiben der Ausgabe »%s«: %m")
INPUT ("(PROGRAM ERROR) No version known!?")
OUTPUT ("(PROGRAM ERROR) Keine Version bekannt!?")
INPUT ("(PROGRAM ERROR) Option should have been recognized!?")
OUTPUT ("(PROGRAM ERROR) Option sollte eigentlich erkannt worden sein!?")
INPUT ("(Unknown object)\n")
OUTPUT ("(Unbekanntes Objekt)\n")
INPUT ("(unknown authentication error - %d)")
OUTPUT ("(unbekannter Fehler bei der Authentifizierung - %d)")
INPUT ("(unknown)")
OUTPUT ("Unbekanntes Signal")
INPUT ("*** The file `%s' is stripped: no detailed analysis possible\n")
OUTPUT ("*** Die Datei »%s« ist gestrippt: keine detaillierte Analyse möglich\n")
INPUT ("*standard input*")
OUTPUT ("*Standardeingabe*")
INPUT ("\
-o OUTPUT-FILE [INPUT-FILE]...\n\
[OUTPUT-FILE [INPUT-FILE]...]")
OUTPUT ("\
-o Ausgabedatei [Eingabedatei]...\n\
[Ausgabedatei [Eingabedatei]...]")
INPUT (".lib section in a.out corrupted")
OUTPUT ("».lib«-Sektion in der »a.out«-Datei ist beschädigt")
INPUT ("; low version = %lu, high version = %lu")
OUTPUT ("; untere Version = %lu, obere Version = %lu")
INPUT ("; why = ")
OUTPUT ("; Ursache = ")
INPUT ("<%s> and <%s> are illegal names for range")
OUTPUT ("<%s> und <%s> sind ungültige Namen für einen Zeichenbereich")
INPUT ("<SP> character must not be in class `%s'")
OUTPUT ("Das Zeichen »<SP>« darf nicht in der Klasse »%s« enthalten sein")
INPUT ("<SP> character not in class `%s'")
OUTPUT ("Das Zeichen »<SP>« ist nicht in der Klasse »%s« enthalten")
INPUT ("?")
OUTPUT ("?")
INPUT ("Aborted")
OUTPUT ("Abgebrochen")
INPUT ("Access Rights : ")
OUTPUT ("Zugriffsrechte: ")
INPUT ("Accessing a corrupted shared library")
OUTPUT ("Zugriff auf eine fehlerhafte oder defekte Shared Library")
INPUT ("Address already in use")
OUTPUT ("Die Adresse wird bereits verwendet")
INPUT ("Address family for hostname not supported")
OUTPUT ("Die Adreßfamilie für Hostnamen wird nicht unterstützt")
INPUT ("Address family not supported by protocol")
OUTPUT ("Die Adreßfamilie wird von der Protokollfamilie nicht unterstützt")
INPUT ("Address family not supported by protocol family")
OUTPUT ("Die Adreßfamilie wird von der Protokollfamilie nicht unterstützt")
INPUT ("Advertise error")
OUTPUT ("Konflikt mit Bekanntmachung")
INPUT ("Alarm clock")
OUTPUT ("Der Wecker klingelt")
INPUT ("Anode table overflow")
OUTPUT ("Überlauf der »anode«-Tabelle")
INPUT ("Arg list too long")
OUTPUT ("Die Argumentliste ist zu lang")
INPUT ("Argument list too long")
OUTPUT ("Die Argumentliste ist zu lang")
INPUT ("Argument out of domain")
OUTPUT ("Das Argument ist außerhalb des Definitionsbereiches")
INPUT ("Attempt to remove a non-empty table")
OUTPUT ("Versuch, eine nicht-leere Tabelle zu löschen")
INPUT ("Attempting to link in more shared libraries than system limit")
OUTPUT ("Versuche mehr Shared Libraries einzubinden als das Systemlimit zuläßt")
INPUT ("Attempting to link in too many shared libraries")
OUTPUT ("Versuch zu viele Shared Libraries einzubinden")
INPUT ("Authentication OK")
OUTPUT ("Authentifizierung OK")
INPUT ("Authentication error")
OUTPUT ("Fehler bei der Authentifizierung")
INPUT ("BOGUS OBJECT\n")
OUTPUT ("BOGUS OBJEKT\n")
INPUT ("Bad address")
OUTPUT ("Ungültige Adresse")
INPUT ("Bad exchange descriptor")
OUTPUT ("Ungültiger Deskriptor zum Datenaustausch")
INPUT ("Bad file descriptor")
OUTPUT ("Ungültiger Dateideskriptor")
INPUT ("Bad file number")
OUTPUT ("Ungültiger Dateideskriptor")
INPUT ("Bad font file format")
OUTPUT ("Ungültiges Font-Dateiformat")
INPUT ("Bad message")
OUTPUT ("Ungültige Nachricht")
INPUT ("Bad request code")
OUTPUT ("Ungültiger Aufruf-Code")
INPUT ("Bad request descriptor")
OUTPUT ("Ungültiger Aufruf-Deskriptor")
INPUT ("Bad system call")
OUTPUT ("Ungültiger Betriebssystemaufruf")
INPUT ("Bad value for ai_flags")
OUTPUT ("Ungültiger Wert für »ai_flags«")
INPUT ("Be strictly POSIX conform")
OUTPUT ("Sei strikt POSIX-konform")
INPUT ("Binary data\n")
OUTPUT ("Binäre Daten\n")
INPUT ("Block device required")
OUTPUT ("Es ist ein Block-Device notwendig")
INPUT ("Broadcast poll problem")
OUTPUT ("Poll-Problem beim Broadcast")
INPUT ("Broken pipe")
OUTPUT ("Datenübergabe unterbrochen (broken pipe)")
INPUT ("Bus error")
OUTPUT ("Bus-Zugriffsfehler")
INPUT ("CDS")
OUTPUT ("CDS")
INPUT ("CPU time limit exceeded")
OUTPUT ("Rechenzeitbegrenzung überschritten")
INPUT ("Cache expired")
OUTPUT ("Der Cache ist verfallen")
INPUT ("Can not access a needed shared library")
OUTPUT ("Auf eine benötigte Shared Library kann nicht zugegriffen werden")
INPUT ("Can not exec a shared library directly")
OUTPUT ("Eine Shared Library kann nicht direkt ausgeführt werden")
INPUT ("Can't bind to server which serves this domain")
OUTPUT ("Kein Server für diese NIS-Domain gefunden")
INPUT ("Can't communicate with portmapper")
OUTPUT ("Keine Kommunikation mit dem Portmapper möglich")
INPUT ("Can't communicate with ypbind")
OUTPUT ("Keine Kommunikation mit »ypbind« möglich")
INPUT ("Can't communicate with ypserv")
OUTPUT ("Keine Kommunikation mit »ypserv« möglich")
INPUT ("Cannot allocate memory")
OUTPUT ("Nicht genügend Hauptspeicher verfügbar")
INPUT ("Cannot assign requested address")
OUTPUT ("Die angeforderte Adresse kann nicht zugewiesen werden")
INPUT ("Cannot create socket for broadcast rpc")
OUTPUT ("Kann den Socket für den Broadcast-RPC nicht erstellen")
INPUT ("Cannot exec a shared library directly")
OUTPUT ("Eine Shared Library kann nicht direkt ausgeführt werden")
INPUT ("Cannot have more than one file generation flag!\n")
OUTPUT ("Mehr als ein File-Generation-Flag angegeben, es ist nur eins erlaubt!\n")
INPUT ("Cannot receive reply to broadcast")
OUTPUT ("Kann die Antwort auf den Broadcast nicht empfangen")
INPUT ("Cannot register service")
OUTPUT ("Kann den Service nicht registrieren")
INPUT ("Cannot send after socket shutdown")
OUTPUT ("Kein Senden nach dem Beenden des Sockets möglich")
INPUT ("Cannot send after transport endpoint shutdown")
OUTPUT ("Ein Senden nach dem Beenden des Sockets ist nicht möglich")
INPUT ("Cannot send broadcast packet")
OUTPUT ("Kann das Broadcast-Paket nicht senden")
INPUT ("Cannot set socket option SO_BROADCAST")
OUTPUT ("Kann die Option »SO_BROADCAST« nicht beim Socket setzen")
INPUT ("Cannot specify more than one input file!\n")
OUTPUT ("Es darf nicht mehr als eine Eingabedatei angegeben werden!\n")
INPUT ("Cannot use netid flag with inetd flag!\n")
OUTPUT ("Kann das »netid«-Flag nicht zusammen mit dem »inetd«-Flag verarbeiten!\n")
INPUT ("Cannot use netid flag without TIRPC!\n")
OUTPUT ("Das »netid«-Flag kann nicht ohne »TIRPC« verwendet werden!\n")
INPUT ("Cannot use table flags with newstyle!\n")
OUTPUT ("Das »table«-flags kann nicht mit »newstyle« verwendet werden!\n")
INPUT ("Channel number out of range")
OUTPUT ("Die Kanalnummer ist außerhalb des gültigen Bereiches")
INPUT ("Character Separator : %c\n")
OUTPUT ("Trennzeichen : %c\n")
INPUT ("Child exited")
OUTPUT ("Der Kind-Prozeß ist beendet")
INPUT ("Client credential too weak")
OUTPUT ("Die Bestätigung des Clients ist zu unsicher")
INPUT ("Columns             :\n")
OUTPUT ("Spalten             :\n")
INPUT ("Communication error on send")
OUTPUT ("Kommunikationsfehler beim Senden")
INPUT ("Compile locale specification")
OUTPUT ("Umwandeln der Lokale-Spezifikation")
INPUT ("Computer bought the farm")
OUTPUT ("Der Computer hat den Bauernhof erworben")
INPUT ("Computing table size for character classes might take a while...")
OUTPUT ("Berechnung der Größe der Tabelle der Zeichenklassen: Dies kann einige Zeit dauern...")
INPUT ("Computing table size for collation information might take a while...")
OUTPUT ("Berechnung der Größe der Tabelle der Sortierinformationen: Dies kann einige Zeit dauern...")
INPUT ("Connection refused")
OUTPUT ("Verbindungsaufbau abgelehnt")
INPUT ("Connection reset by peer")
OUTPUT ("Die Verbindung wurde vom Kommunikationspartner zurückgesetzt")
INPUT ("Connection timed out")
OUTPUT ("Die Wartezeit für die Verbindung ist abgelaufen")
INPUT ("Continued")
OUTPUT ("Fortgesetzt")
INPUT ("Convert encoding of given files from one encoding to another.")
OUTPUT ("Konvertiert die Kodierung von Dateien in eine andere Kodierung.")
INPUT ("Convert key to lower case")
OUTPUT ("Übersetze den Schlüssel in Kleinbuchstaben")
INPUT ("\
Copyright (C) %s Free Software Foundation, Inc.\n\
This is free software; see the source for copying conditions.  There is NO\n\
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n")
OUTPUT ("\
Copyright © %s Free Software Foundation, Inc.\n\
Dies ist freie Software; in den Quellen befinden sich die Lizenzbedingungen.\n\
Es gibt KEINERLEI Garantie; nicht einmal für die TAUGLICHKEIT oder\n\
VERWENDBARKEIT FÜR EINEN ANGEGEBENEN ZWECK.\n")
INPUT ("Could not create log file \"%s\"")
OUTPUT ("Kann die Logdatei »%s« nicht erstellen")
INPUT ("Create C header file NAME containing symbol definitions")
OUTPUT ("Erzeuge die C Headerdatei NAME mit den Symboldefinitionen")
INPUT ("Create output even if warning messages were issued")
OUTPUT ("Die Ausgabedatei wird erzeugt, obwohl Warnungen ausgegeben wurden")
INPUT ("Create simple DB database from textual input.")
OUTPUT ("Erstellt eine einfach DB Datenbank aus einer Text-Eingabe.")
INPUT ("Creation Time : %s")
OUTPUT ("Erstellungszeit: %s")
INPUT ("Cross-device link")
OUTPUT ("Ungültiger Link über Gerätegrenzen hinweg")
INPUT ("DES entry for netname %s not unique\n")
OUTPUT ("Der DES-Eintrag für den netname »%s« ist nicht eindeutig\n")
INPUT ("DIRECTORY\n")
OUTPUT ("VERZEICHNIS\n")
INPUT ("DNANS")
OUTPUT ("DNANS")
INPUT ("DNS")
OUTPUT ("DNS")
INPUT ("Database for table does not exist")
OUTPUT ("Die Datenbank für die Tabelle existiert nicht")
INPUT ("Database is busy")
OUTPUT ("Die Databank ist belegt")
INPUT ("Deadlock situation detected/avoided")
OUTPUT ("Verklemmung erkannt/vermieden")
INPUT ("Default Access rights :\n")
OUTPUT ("Standard-Zugriffsrechte :\n")
INPUT ("Destination address required")
OUTPUT ("Es ist eine Zieladresse notwendig")
INPUT ("Device busy")
OUTPUT ("Das Gerät oder die Ressource ist belegt")
INPUT ("Device not a stream")
OUTPUT ("Das Gerät ist kein Stream")
INPUT ("Device not configured")
OUTPUT ("Das Gerät ist nicht konfiguriert")
INPUT ("Device or resource busy")
OUTPUT ("Das Gerät oder die Ressource ist belegt")
INPUT ("Diffie-Hellmann (%d bits)\n")
OUTPUT ("Diffie-Hellmann (%d Bits)\n")
INPUT ("Directory     : %s\n")
OUTPUT ("Verzeichnis   : %s\n")
INPUT ("Directory not empty")
OUTPUT ("Das Verzeichnis ist nicht leer")
INPUT ("Disc quota exceeded")
OUTPUT ("Der zugewiesene Plattenplatz (Quota) ist überschritten")
INPUT ("Disk quota exceeded")
OUTPUT ("Der zugewiesene Plattenplatz (Quota) ist überschritten")
INPUT ("Do not fork and display messages on the current tty")
OUTPUT ("Führe kein »fork()« aus und zeige Nachrichten auf dem aktuellen tty an")
INPUT ("Do not print messages while building database")
OUTPUT ("Gebe keine Nachrichten aus, während die Datenbank aufgebaut wird")
INPUT ("Do not use existing catalog, force new output file")
OUTPUT ("Verwende nicht den existierenden Katalog; erzwinge eine neue Ausgabedatei")
INPUT ("Domain not bound")
OUTPUT ("Die Domain wurde nicht zugewiesen")
INPUT ("EMT trap")
OUTPUT ("EMT-Trap")
INPUT ("ENTRY\n")
OUTPUT ("ENTRY\n")
INPUT ("Encrypted data\n")
OUTPUT ("Verschlüsselte Daten\n")
INPUT ("Entry/table type mismatch")
OUTPUT ("Die Typen des Eintrages/der Tabelle passen nicht zusammen")
INPUT ("Error 0")
OUTPUT ("Fehler 0")
INPUT ("Error 100")
OUTPUT ("Fehler 100")
INPUT ("Error 101")
OUTPUT ("Fehler 101")
INPUT ("Error 102")
OUTPUT ("Fehler 102")
INPUT ("Error 103")
OUTPUT ("Fehler 103")
INPUT ("Error 104")
OUTPUT ("Fehler 104")
INPUT ("Error 105")
OUTPUT ("Fehler 105")
INPUT ("Error 106")
OUTPUT ("Fehler 106")
INPUT ("Error 107")
OUTPUT ("Fehler 107")
INPUT ("Error 108")
OUTPUT ("Fehler 108")
INPUT ("Error 109")
OUTPUT ("Fehler 109")
INPUT ("Error 110")
OUTPUT ("Fehler 110")
INPUT ("Error 111")
OUTPUT ("Fehler 111")
INPUT ("Error 112")
OUTPUT ("Fehler 112")
INPUT ("Error 113")
OUTPUT ("Fehler 113")
INPUT ("Error 114")
OUTPUT ("Fehler 114")
INPUT ("Error 115")
OUTPUT ("Fehler 115")
INPUT ("Error 116")
OUTPUT ("Fehler 116")
INPUT ("Error 117")
OUTPUT ("Fehler 117")
INPUT ("Error 118")
OUTPUT ("Fehler 118")
INPUT ("Error 119")
OUTPUT ("Fehler 119")
INPUT ("Error 136")
OUTPUT ("Fehler 136")
INPUT ("Error 142")
OUTPUT ("Fehler 142")
INPUT ("Error 58")
OUTPUT ("Fehler 58")
INPUT ("Error 59")
OUTPUT ("Fehler 59")
INPUT ("Error 72")
OUTPUT ("Fehler 72")
INPUT ("Error 73")
OUTPUT ("Fehler 73")
INPUT ("Error 75")
OUTPUT ("Fehler 75")
INPUT ("Error 76")
OUTPUT ("Fehler 76")
INPUT ("Error 91")
OUTPUT ("Fehler 91")
INPUT ("Error 92")
OUTPUT ("Fehler 92")
INPUT ("Error in RPC subsystem")
OUTPUT ("Fehler im RPC Subsystem: ")
INPUT ("Error in accessing NIS+ cold start file.  Is NIS+ installed?")
OUTPUT ("Fehler beim Zugriff auf die NIS+ Kaltstart-Datei.  Ist NIS+ installiert?")
INPUT ("Error in unknown error system: ")
OUTPUT ("Fehler in unbekanntem Fehler-System: ")
INPUT ("Error while talking to callback proc")
OUTPUT ("Fehler bei der Kommunikation mit der Callback-Prozedur")
INPUT ("Error: .netrc file is readable by others.")
OUTPUT ("Fehler: Die Datei ».netrc« ist für andere Benutzer lesbar.")
INPUT ("Exchange full")
OUTPUT ("Vermittlung ist überfüllt")
INPUT ("Exec format error")
OUTPUT ("Fehler im Format der Programmdatei")
INPUT ("FATAL: system does not define `_POSIX2_LOCALEDEF'")
OUTPUT ("Fataler Fehler: Das System definiert das Symbol »_POSIX2_LOCALEDEF« nicht")
INPUT ("FILE")
OUTPUT ("Datei")
INPUT ("FILE contains mapping from symbolic names to UCS4 values")
OUTPUT ("FILE enthält Zuordnungen von symbolischen Namen zu UCS4-Werten")
INPUT ("Failed (unspecified error)")
OUTPUT ("Fehlgeschlagen (Fehler nicht genau zu spezifizieren)")
INPUT ("File descriptor in bad state")
OUTPUT ("Die Dateizugriffsnummer ist ein schlechter Verfassung")
INPUT ("File exists")
OUTPUT ("Die Datei existiert bereits")
INPUT ("File locking deadlock")
OUTPUT ("Verklemmung beim Datei-Locking")
INPUT ("File locking deadlock error")
OUTPUT ("Verklemmung beim Datei-Locking")
INPUT ("File name too long")
OUTPUT ("Der Dateiname ist zu lang")
INPUT ("File size limit exceeded")
OUTPUT ("Die maximale Dateigröße ist überschritten")
INPUT ("File table overflow")
OUTPUT ("Überlauf der Datei-Deskriptoren-Tabelle")
INPUT ("File too large")
OUTPUT ("Die Datei ist zu groß")
INPUT ("First/next chain broken")
OUTPUT ("Die Verkettung mittels First/Next ist defekt")
INPUT ("Floating point exception")
OUTPUT ("Gleitkomma-Ausnahme")
INPUT ("Full resync required for directory")
OUTPUT ("Vollständige Resynchronisation für das Verzeichnis ist erforderlich")
INPUT ("Function not implemented")
OUTPUT ("Die angeforderte Funktion ist nicht implementiert")
INPUT ("GROUP\n")
OUTPUT ("GROUP\n")
INPUT ("Garbage in ARGP_HELP_FMT: %s")
OUTPUT ("Unsinnige Daten in ARGP_HELP_FMT: %s")
INPUT ("\
Generate message catalog.\\vIf INPUT-FILE is -, input is read from standard input.  If OUTPUT-FILE\n\
is -, output is written to standard output.\n")
OUTPUT ("\
Generiere einen Message-Katalog.\\vWenn als INPUT-FILE - angegeben wird, wird von der Standardeingabe gelesen.  Wenn die OUTPUT-FILE\n\
- ist, wird auf die Standardausgabe geschrieben.\n")
INPUT ("Generic system error")
OUTPUT ("Allgemeiner Systemfehler")
INPUT ("Get locale-specific information.")
OUTPUT ("Hole Lokale-spezifische Informationen.")
INPUT ("Give a short usage message")
OUTPUT ("Gibt kurze Bedienungshinweise aus")
INPUT ("Give this help list")
OUTPUT ("Gibt diese Hilfe aus")
INPUT ("Gratuitous error")
OUTPUT ("Irgendein Fehler")
INPUT ("Group         : %s\n")
OUTPUT ("Gruppe        : %s\n")
INPUT ("Group Flags :")
OUTPUT ("Gruppen Flags:")
INPUT ("Group entry for \"%s.%s\" group:\n")
OUTPUT ("Gruppen-Eintrag für die Gruppe »%s.%s«:\n")
INPUT ("Hang for SECS seconds (default 3600)")
OUTPUT ("Warte für SECS Sekunden (Standardwert ist 3600)")
INPUT ("Hangup")
OUTPUT ("Aufgelegt")
INPUT ("Haven't found \"%d\" in group cache!")
OUTPUT ("Habe »%d« nicht im Group-Cache gefunden!")
INPUT ("Haven't found \"%d\" in password cache!")
OUTPUT ("Habe »%d« nicht im Password-Cache gefunden!")
INPUT ("Haven't found \"%s\" in group cache!")
OUTPUT ("Habe »%s« nicht im Group-Cache gefunden!")
INPUT ("Haven't found \"%s\" in hosts cache!")
OUTPUT ("Habe »%s« nicht im Host-Cache gefunden!")
INPUT ("Haven't found \"%s\" in password cache!")
OUTPUT ("Habe »%s« nicht im Password-Cache gefunden!")
INPUT ("Host is down")
OUTPUT ("Der Rechner ist nicht aktiv")
INPUT ("Host name lookup failure")
OUTPUT ("Fehler beim Auflösen des Hostnamens")
INPUT ("I/O error")
OUTPUT ("Ein-/Ausgabefehler")
INPUT ("I/O possible")
OUTPUT ("Ein-/Ausgabe ist möglich")
INPUT ("\
INPUT-FILE OUTPUT-FILE\n\
-o OUTPUT-FILE INPUT-FILE\n\
-u INPUT-FILE")
OUTPUT ("\
Eingabedatei Ausgabedatei\n\
-o Ausgabedatei Eingabedatei\n\
-u Eingabedatei")
INPUT ("IOT trap")
OUTPUT ("Ein-/Ausgabe-Trap (IOT)")
INPUT ("IVY")
OUTPUT ("IVY")
INPUT ("Identifier removed")
OUTPUT ("Bezeichner wurde entfernt")
INPUT ("Illegal byte sequence")
OUTPUT ("Ungültige Byte-Folge")
INPUT ("Illegal instruction")
OUTPUT ("Ungültiger Maschinenbefehl")
INPUT ("Illegal object type for operation")
OUTPUT ("Ungültiger Objekt-Typ für die angeforderte Operation")
INPUT ("Illegal seek")
OUTPUT ("Nicht erlaubter Seek")
INPUT ("Inappropriate file type or format")
OUTPUT ("Unpassender Dateityp oder unpassendes Dateiformat")
INPUT ("Inappropriate ioctl for device")
OUTPUT ("Unpassender IOCTL (I/O-Control) für das Gerät")
INPUT ("Inappropriate operation for background process")
OUTPUT ("Unpassende Operation für den Hintergrundprozeß")
INPUT ("Information request")
OUTPUT ("Informationsanfrage")
INPUT ("Information:")
OUTPUT ("Information:")
INPUT ("Input Files:")
OUTPUT ("Eingabedateien:")
INPUT ("Input/Output format specification:")
OUTPUT ("Beschreibung des Ein-/Ausgabe-Formates:")
INPUT ("Input/output error")
OUTPUT ("Eingabe-/Ausgabefehler")
INPUT ("Internal NIS error")
OUTPUT ("Interner NIS-Fehler")
INPUT ("Internal ypbind error")
OUTPUT ("Interner Fehler in »ypbind«")
INPUT ("Interrupt")
OUTPUT ("Unterbrechung")
INPUT ("Interrupted system call")
OUTPUT ("Unterbrechung während des Betriebssystemaufrufs")
INPUT ("Interrupted system call should be restarted")
OUTPUT ("Der unterbrochene Betriebssystemaufruf sollte neu gestartet werden")
INPUT ("Invalid argument")
OUTPUT ("Das Argument ist ungültig")
INPUT ("Invalid back reference")
OUTPUT ("Ungültiger Verweis zurück")
INPUT ("Invalid character class name")
OUTPUT ("Ungültiger Name für eine Zeichenklasse")
INPUT ("Invalid client credential")
OUTPUT ("Die Bestätigung des Clients ist ungültig")
INPUT ("Invalid client verifier")
OUTPUT ("Ungültige Überprüfung des Clients")
INPUT ("Invalid collation character")
OUTPUT ("Ungültiges Sortierzeichen")
INPUT ("Invalid content of \\{\\}")
OUTPUT ("Ungültiger Inhalt von »\\{\\}«")
INPUT ("Invalid cross-device link")
OUTPUT ("Ungültiger Link über Gerätegrenzen hinweg")
INPUT ("Invalid exchange")
OUTPUT ("Ungültiger Austausch")
INPUT ("Invalid object for operation")
OUTPUT ("Ungültiges Objekt für diese Operation")
INPUT ("Invalid or incomplete multibyte or wide character")
OUTPUT ("Ungültiges oder unvollständiges Multi-Byte- oder Wide-Zeichen")
INPUT ("Invalid preceding regular expression")
OUTPUT ("Der vorherige reguläre Ausdruck ist nicht korrekt.")
INPUT ("Invalid range end")
OUTPUT ("Das Ende des angegebenen Intervalls ist nicht gültig")
INPUT ("Invalid regular expression")
OUTPUT ("Ungültiger regulärer Ausdruck")
INPUT ("Invalid request code")
OUTPUT ("Ungültiger Aufruf-Code")
INPUT ("Invalid request descriptor")
OUTPUT ("Ungültiger Aufruf-Deskriptor")
INPUT ("Invalid server verifier")
OUTPUT ("Ungültige Überprüfung des Servers")
INPUT ("Invalid slot")
OUTPUT ("Ungültiger Slot")
INPUT ("Invalidate the specified cache")
OUTPUT ("Der angegebene Cache wird verworfen")
INPUT ("Is a directory")
OUTPUT ("Ist ein Verzeichnis")
INPUT ("Is a name file")
OUTPUT ("Ist eine »named file«")
INPUT ("Is a named type file")
OUTPUT ("Ist eine »named type file«")
INPUT ("Kerberos.\n")
OUTPUT ("Kerberos.\n")
INPUT ("Killed")
OUTPUT ("Getötet")
INPUT ("LINK\n")
OUTPUT ("LINK\n")
INPUT ("LOCAL entry for UID %d in directory %s not unique\n")
OUTPUT ("Der LOCAL Eintrag für die UID »%d« im Verzeichnis »%s« ist nicht eindeutig\n")
INPUT ("Level 2 halted")
OUTPUT ("Level 2 angehalten")
INPUT ("Level 2 not synchronized")
OUTPUT ("Level 2 ist nicht synchronisiert")
INPUT ("Level 3 halted")
OUTPUT ("Level 3 angehalten")
INPUT ("Level 3 reset")
OUTPUT ("Level 3 zurückgesetzt")
INPUT ("Link has been severed")
OUTPUT ("Der Link wurde beschädigt")
INPUT ("Link number out of range")
OUTPUT ("Die Link-Nummer ist außerhalb des gültigen Bereiches")
INPUT ("Link points to illegal name")
OUTPUT ("Der Link verweist auf einen ungültigen Namen")
INPUT ("Linked Object Type : ")
OUTPUT ("Verbundener Objekt-Typ : ")
INPUT ("Linked to : %s\n")
OUTPUT ("Verbunden zu : %s\n")
INPUT ("Local domain name not set")
OUTPUT ("Der lokale Domain-Name ist nicht eingetragen")
INPUT ("Local resource allocation failure")
OUTPUT ("Lokaler Fehler bei der Ressourcenreservierung")
INPUT ("Machine is not on the network")
OUTPUT ("Die Maschine ist nicht an das Netzwerk angeschlossen")
INPUT ("Malformed name, or illegal name")
OUTPUT ("Ungültiger oder fehlerhafter Name")
INPUT ("Mandatory or optional arguments to long options are also mandatory or optional for any corresponding short options.")
OUTPUT ("Obligatorische oder optionale Argumente von langen Optionen sind ebenfalls obligatorische bzw. optionale Argumente für jede zugehörige kurze Option.")
INPUT ("Master Server :\n")
OUTPUT ("Master Server :\n")
INPUT ("Master server busy, full dump rescheduled.")
OUTPUT ("Der Master-Server ist beschäftigt, vollständiger Dump neu eingeplant.")
INPUT ("Memory allocation failure")
OUTPUT ("Fehler beim Anfordern von Hauptspeicher")
INPUT ("Memory exhausted")
OUTPUT ("Kein Hauptspeicher mehr verfügbar")
INPUT ("Message tables full")
OUTPUT ("Die Nachrichtentabelle ist voll")
INPUT ("Message too long")
OUTPUT ("Die Nachricht ist zu lang")
INPUT ("Missing or malformed attribute")
OUTPUT ("Fehlendes oder fehlerhaftes Attribut")
INPUT ("Mod. Time     : %s")
OUTPUT ("Mod. Zeit     : %s")
INPUT ("Modification failed")
OUTPUT ("Modifikation fehlgeschlagen")
INPUT ("Modify operation failed")
OUTPUT ("Die Veränderung ist fehlgeschlagen")
INPUT ("Modify output format:")
OUTPUT ("Modifiziere Ausgabe-Format:")
INPUT ("Multihop attempted")
OUTPUT ("Ein »Multihop« wurde versucht")
INPUT ("NAME")
OUTPUT ("NAME")
INPUT ("\
NAME\n\
[-a|-m]")
OUTPUT ("\
Name\n\
[-a|-m]")
INPUT ("NIS")
OUTPUT ("NIS")
INPUT ("NIS client/server version mismatch - can't supply service")
OUTPUT ("NIS-Client/Server-Versionen passen nicht zusammen - kein Service möglich")
INPUT ("NIS map database is bad")
OUTPUT ("Die Datenbank mit der NIS-Map ist ungültig")
INPUT ("NIS+ operation failed")
OUTPUT ("NIS+-Operation fehlgeschlagen")
INPUT ("NIS+ servers unreachable")
OUTPUT ("Die NIS+-Server sind nicht erreichbar")
INPUT ("NIS+ service is unavailable or not installed")
OUTPUT ("Der NIS+ Dienst ist nicht verfügbar oder nicht installiert")
INPUT ("NO OBJECT\n")
OUTPUT ("KEIN OBJEKT\n")
INPUT ("NUMBER")
OUTPUT ("NUMMER")
INPUT ("Name : `%s'\n")
OUTPUT ("Name : »%s«\n")
INPUT ("Name Service Cache Daemon.")
OUTPUT ("Name Service Cache Daemon.")
INPUT ("Name not served by this server")
OUTPUT ("Der Name wird nicht von diesem Server verwaltet")
INPUT ("Name not unique on network")
OUTPUT ("Der Name ist im Netzwerk nicht eindeutig")
INPUT ("Name or service not known")
OUTPUT ("Der Name oder der Dienst ist nicht bekannt")
INPUT ("Name/entry isn't unique")
OUTPUT ("Der Name bzw. Eintrag ist nicht eindeutig")
INPUT ("Named object is not searchable")
OUTPUT ("Das benannte Objekt ist nicht durchsuchbar")
INPUT ("Need authenticator")
OUTPUT ("Authentikator benötigt")
INPUT ("Network dropped connection because of reset")
OUTPUT ("Das Netzwerk hat die Verbindung nach einem Reset beendet")
INPUT ("Network dropped connection on reset")
OUTPUT ("Das Netzwerk hat die Verbindung nach einem Reset verloren")
INPUT ("Network is down")
OUTPUT ("Das Netzwerk ist nicht aktiv")
INPUT ("Network is unreachable")
OUTPUT ("Das Netzwerk ist nicht erreichbar")
INPUT ("No CSI structure available")
OUTPUT ("Keine »CSI«-Struktur verfügbar")
INPUT ("No XENIX semaphores available")
OUTPUT ("Keine XENIX-Semaphoren verfügbar")
INPUT ("No address associated with hostname")
OUTPUT ("Zu diesem Hostnamen gehört keine Adresse")
INPUT ("No address associated with name")
OUTPUT ("Zu diesem Namen gehört keine Adresse")
INPUT ("No anode")
OUTPUT ("Keine Anode")
INPUT ("No buffer space available")
OUTPUT ("Kein Hauptspeicher für den Puffer verfügbar")
INPUT ("No child processes")
OUTPUT ("Keine Kind-Prozesse")
INPUT ("No data available")
OUTPUT ("Keine Daten verfügbar")
INPUT ("No file space on server")
OUTPUT ("Auf dem Server ist kein Speicherplatz mehr verfügbar")
INPUT ("No locks available")
OUTPUT ("Keine Sperren verfügbar")
INPUT ("No match")
OUTPUT ("Keine Übereinstimmung gefunden")
INPUT ("No medium found")
OUTPUT ("Kein Medium gefunden")
INPUT ("No message of desired type")
OUTPUT ("Keine Nachricht des gewünschten Typs")
INPUT ("No more records in map database")
OUTPUT ("Keine weiteren Sätze in der Map-Datenbank")
INPUT ("No previous regular expression")
OUTPUT ("Es wurde bisher noch kein regulärer Ausdruck definiert")
INPUT ("No record locks available")
OUTPUT ("Keine Datensatz-Sperren verfügbar")
INPUT ("No remote programs registered.\n")
OUTPUT ("Es sind keine entfernten Programme registriert.\n")
INPUT ("No route to host")
OUTPUT ("Keine Route zum Zielrechner")
INPUT ("No space left on device")
OUTPUT ("Auf dem Gerät ist kein Speicherplatz mehr verfügbar")
INPUT ("No such device")
OUTPUT ("Kein passendes Gerät gefunden")
INPUT ("No such device or address")
OUTPUT ("Kein passendes Gerät bzw. keine passende Adresse gefunden")
INPUT ("No such file or directory")
OUTPUT ("Datei oder Verzeichnis nicht gefunden")
INPUT ("No such key in map")
OUTPUT ("Kein passender Schlüssel in der Map")
INPUT ("No such map in server's domain")
OUTPUT ("Keine passende Map in der Domain des Servers")
INPUT ("No such process")
OUTPUT ("Kein passender Prozeß gefunden")
INPUT ("Non NIS+ namespace encountered")
OUTPUT ("Kein NIS+-Namespace gefunden")
INPUT ("Non-recoverable failure in name resolution")
OUTPUT ("Nicht-behebbarer Fehler in der Namensauflösung")
INPUT ("None.\n")
OUTPUT ("Keine.\n")
INPUT ("Not a XENIX named type file")
OUTPUT ("Keine XENIX »named type« Datei")
INPUT ("Not a data message")
OUTPUT ("Das ist keine »data message«")
INPUT ("Not a directory")
OUTPUT ("Ist kein Verzeichnis")
INPUT ("Not a name file")
OUTPUT ("Keine »named file«")
INPUT ("Not a stream device")
OUTPUT ("Ist kein Stream-Gerät")
INPUT ("Not available")
OUTPUT ("Nicht verfügbar")
INPUT ("Not enough space")
OUTPUT ("Nicht genugend (Speicher-)Platz")
INPUT ("Not found")
OUTPUT ("Nicht gefunden")
INPUT ("Not found, no such name")
OUTPUT ("Nicht gefunden, kein solcher Name")
INPUT ("Not master server for this domain")
OUTPUT ("Kein Master-Server für diese Domain")
INPUT ("Not owner")
OUTPUT ("Bin nicht der Eigentümer")
INPUT ("Not supported")
OUTPUT ("Nicht unterstützt")
INPUT ("Number of Columns   : %d\n")
OUTPUT ("Anzahl der Spalten  : %d\n")
INPUT ("Number of objects : %u\n")
OUTPUT ("Anzahl der Objekte: %u\n")
INPUT ("Number of symbolic links encountered during path name traversal exceeds MAXSYMLINKS")
OUTPUT ("Die Anzahl der symbolischen Link, die beim Durchgehen des Pfades gefunden wurden, überschreitet den Wert MAXSYMLINKS")
INPUT ("Numerical argument out of domain")
OUTPUT ("Das numerische Argument ist außerhalb des Definitionsbereiches")
INPUT ("Numerical result out of range")
OUTPUT ("Das numerische Ergebnis ist außerhalb des gültigen Bereiches")
INPUT ("Object #%d:\n")
OUTPUT ("Objekt #%d:\n")
INPUT ("Object Name   : %s\n")
OUTPUT ("Objekt-Name   : %s\n")
INPUT ("Object Type   : ")
OUTPUT ("Objekt-Typ    : ")
INPUT ("Object is remote")
OUTPUT ("Das Objekt ist remote")
INPUT ("Object with same name exists")
OUTPUT ("Ein Objekt mit demselben Namen existiert bereits")
INPUT ("Odd number of quotation marks")
OUTPUT ("Ungerade Anzahl von Anführungszeichen")
INPUT ("Only root is allowed to use this option!")
OUTPUT ("Nur der Systemverwalter »root« darf diese Option benutzen!")
INPUT ("Operation already in progress")
OUTPUT ("Die Operation wird bereits ausgeführt")
INPUT ("Operation canceled")
OUTPUT ("Die Operation wird abgebrochen")
INPUT ("Operation not applicable")
OUTPUT ("Die Operation ist nicht anwendbar")
INPUT ("Operation not permitted")
OUTPUT ("Die Operation ist nicht erlaubt")
INPUT ("Operation not supported")
OUTPUT ("Die Operation wird nicht unterstützt")
INPUT ("Operation not supported on transport endpoint")
OUTPUT ("Die Operation wird am Transport-Endpunkt nicht unterstützt")
INPUT ("Operation now in progress")
OUTPUT ("Die Operation ist jetzt in Bearbeitung")
INPUT ("Operation would block")
OUTPUT ("Die Operation würde blockieren")
INPUT ("Option not supported by protocol")
OUTPUT ("Die Option wird vom Protokoll nicht unterstützt")
INPUT ("Out of stream resources")
OUTPUT ("Keine Stream-Ressourcen mehr verfügbar")
INPUT ("Out of streams resources")
OUTPUT ("Keine Stream-Ressourcen mehr verfügbar")
INPUT ("Output control:")
OUTPUT ("Ausgabesteuerung:")
INPUT ("Output selection:")
OUTPUT ("Ausgabeselektion:")
INPUT ("Owner         : %s\n")
OUTPUT ("Eigentümer    : %s\n")
INPUT ("PRIVATE\n")
OUTPUT ("PRIVAT\n")
INPUT ("Package not installed")
OUTPUT ("Das Zusatzpacket ist nicht installiert")
INPUT ("Parse error: %s")
OUTPUT ("Syntax-Fehler: %s")
INPUT ("Partial success")
OUTPUT ("Teilweise erfolgreich")
INPUT ("Passed object is not the same object on server")
OUTPUT ("Das übergebene Objekt ist nicht dasselbe Objekt auf dem Server")
INPUT ("Permission denied")
OUTPUT ("Keine Berechtigung")
INPUT ("Power failure")
OUTPUT ("Fehler in der Stromversorgung")
INPUT ("Premature end of regular expression")
OUTPUT ("Unerwartetes Ende des regulären Ausdruckes")
INPUT ("Print content of database file, one entry a line")
OUTPUT ("Gibt den Inhalt der Datenbank-Datei aus, je Eintrag eine Zeile")
INPUT ("Print current configuration statistic")
OUTPUT ("Gibt die aktuelle Konfigurationsstatistik aus")
INPUT ("Print more messages")
OUTPUT ("Gibt mehr Nachrichten aus")
INPUT ("Print program version")
OUTPUT ("Gib die Programmversion aus")
INPUT ("Probable success")
OUTPUT ("Möglicherweise erfolgreich")
INPUT ("Probably not found")
OUTPUT ("Möglicherweise nicht gefunden")
INPUT ("Profiling timer expired")
OUTPUT ("Zeitnehmer zur Laufzeitbestimmung ist abgelaufen")
INPUT ("Protocol driver not attached")
OUTPUT ("Das Protokoll ist nicht verfügbar")
INPUT ("Protocol error")
OUTPUT ("Protokollfehler")
INPUT ("Protocol family not supported")
OUTPUT ("Die Protokollfamilie wird nicht unterstützt")
INPUT ("Protocol not available")
OUTPUT ("Das Protokoll ist nicht verfügbar")
INPUT ("Protocol not supported")
OUTPUT ("Das Protokoll wird nicht unterstützt")
INPUT ("Protocol wrong type for socket")
OUTPUT ("Das Protokoll paßt nicht zu dem Socket")
INPUT ("Query illegal for named table")
OUTPUT ("Die Abfrage ist für die angegebene Tabelle nicht erlaubt")
INPUT ("Quit")
OUTPUT ("Verlassen")
INPUT ("RFS specific error")
OUTPUT ("RFS-spezifischer Fehler")
INPUT ("RPC bad procedure for program")
OUTPUT ("RPC: ungültige Prozedur für das Programm")
INPUT ("RPC failure on NIS operation")
OUTPUT ("RPC: Fehler bei einer NIS-Operation")
INPUT ("RPC program not available")
OUTPUT ("RPC: Programm nicht verfügbar")
INPUT ("RPC program version wrong")
OUTPUT ("RPC: Die Programmversion ist falsch")
INPUT ("RPC struct is bad")
OUTPUT ("RPC: Die Struktur ist ungültig")
INPUT ("RPC version wrong")
OUTPUT ("RPC: falsche Version")
INPUT ("RPC: (unknown error code)")
OUTPUT ("RPC: (Unbekannter Fehlercode)")
INPUT ("RPC: Authentication error")
OUTPUT ("RPC: Fehler bei der Authentifizierung")
INPUT ("RPC: Can't decode result")
OUTPUT ("RPC: Kann das Ergebnis nicht dekodieren")
INPUT ("RPC: Can't encode arguments")
OUTPUT ("RPC: Kann die Argumente nicht kodieren")
INPUT ("RPC: Failed (unspecified error)")
OUTPUT ("RPC: Fehlgeschlagen (Fehler nicht zu spezifizieren)")
INPUT ("RPC: Incompatible versions of RPC")
OUTPUT ("RPC: Die RPC-Versionen sind nicht kompatibel")
INPUT ("RPC: Port mapper failure")
OUTPUT ("RPC: Fehler des Portmappers")
INPUT ("RPC: Procedure unavailable")
OUTPUT ("RPC: Prozedur nicht verfügbar")
INPUT ("RPC: Program not registered")
OUTPUT ("RPC: Programm nicht registriert")
INPUT ("RPC: Program unavailable")
OUTPUT ("RPC: Programm nicht verfügbar")
INPUT ("RPC: Program/version mismatch")
OUTPUT ("RPC: Programm/Version nicht passend")
INPUT ("RPC: Remote system error")
OUTPUT ("RPC: Fehler des entfernten Systems")
INPUT ("RPC: Server can't decode arguments")
OUTPUT ("RPC: Server kann die Argumente nicht dekodieren")
INPUT ("RPC: Success")
OUTPUT ("RPC: Erfolgreich")
INPUT ("RPC: Timed out")
OUTPUT ("RPC: Wartezeit abgelaufen")
INPUT ("RPC: Unable to receive")
OUTPUT ("RPC: Kann nicht empfangen")
INPUT ("RPC: Unable to send")
OUTPUT ("RPC: Kann nicht senden")
INPUT ("RPC: Unknown host")
OUTPUT ("RPC: Unbekannter Rechner")
INPUT ("RPC: Unknown protocol")
OUTPUT ("RPC: Unbekanntes Protokoll")
INPUT ("RSA (%d bits)\n")
OUTPUT ("RSA (%d Bits)\n")
INPUT ("RTLD_NEXT used in code not dynamically loaded")
OUTPUT ("»RTLD_NEXT« wird in Code verwendet, der nicht dynamisch geladen ist")
INPUT ("Read and display shared object profiling data")
OUTPUT ("Lies und gib die Profiling-Informationen von Shared Objects aus.")
INPUT ("Read configuration data from NAME")
OUTPUT ("Lies die Konfiguration aus NAME")
INPUT ("Read-only file system")
OUTPUT ("Das Dateisystem ist nur lesbar")
INPUT ("Real-time signal %d")
OUTPUT ("Real-Time Signal %d")
INPUT ("Regular expression too big")
OUTPUT ("Der reguläre Ausdruck ist zu groß")
INPUT ("Remote I/O error")
OUTPUT ("Ein-/Ausgabefehler der Gegenstelle (remote)")
INPUT ("Remote address changed")
OUTPUT ("Die Adresse der Gegenstelle hat sich geändert")
INPUT ("Remove password or make file unreadable by others.")
OUTPUT ("Das Paßwort löschen oder die Datei für andere nicht lesbar anlegen.")
INPUT ("Reopening shared object `%s' failed")
OUTPUT ("Erneutes Öffnen des Shared Objects »%s« ist mißlungen")
INPUT ("Replicate :\n")
OUTPUT ("Replik :\n")
INPUT ("Report bugs to %s.\n")
OUTPUT ("Fehlermeldungen bitte an »%s« senden.\n")
INPUT ("Report bugs using the `glibcbug' script to <bugs@gnu.org>.\n")
OUTPUT ("Fehler bitte mit dem »glibcbug«-Skript an <bugs@gnu.org> melden.\n")
INPUT ("Request arguments bad")
OUTPUT ("Die Request-Argumente sind ungültig")
INPUT ("Reserved for future use")
OUTPUT ("Reserviert für eine zukünftige Verwendung")
INPUT ("Resolver Error 0 (no error)")
OUTPUT ("Fehler 0 des Resolvers (kein Fehler)")
INPUT ("Resolver internal error")
OUTPUT ("Interner Fehler des Resolvers")
INPUT ("Resource deadlock avoided")
OUTPUT ("Verklemmung beim Zugriff auf eine Ressource vermieden")
INPUT ("Resource lost")
OUTPUT ("Die Ressource ist verlorengegangen")
INPUT ("Resource temporarily unavailable")
OUTPUT ("Die Ressource ist zur Zeit nicht verfügbar")
INPUT ("Result too large")
OUTPUT ("Das Ergebnis ist zu groß")
INPUT ("Results sent to callback proc")
OUTPUT ("Ergebnisse an die Callback-Prozedur gesendet")
INPUT ("SHOBJ [PROFDATA]")
OUTPUT ("SHOBJ [PROFDATA]")
INPUT ("SUNYP")
OUTPUT ("SUNYP")
INPUT ("Search Path         : %s\n")
OUTPUT ("Suchpfad            : %s\n")
INPUT ("Segmentation fault")
OUTPUT ("Speicherzugriffsfehler")
INPUT ("Server busy, try again")
OUTPUT ("Der Server ist zur Zeit beschäftigt, bitte nochmal versuchen")
INPUT ("Server out of memory")
OUTPUT ("Der Hauptspeicher des Servers ist erschöpft")
INPUT ("Server rejected credential")
OUTPUT ("Der Server hat die Bestätigung zurückgewiesen")
INPUT ("Server rejected verifier")
OUTPUT ("Der Server hat die Überprüfung zurückgewiesen")
INPUT ("Servname not supported for ai_socktype")
OUTPUT ("»Servname« wird für »ai_soctype« nicht unterstützt")
INPUT ("Set the program name")
OUTPUT ("Setzt den Programm-Namen")
INPUT ("Shut the server down")
OUTPUT ("Stoppt den Server")
INPUT ("Signal 0")
OUTPUT ("Signal 0")
INPUT ("Socket operation on non-socket")
OUTPUT ("Socket-Operation an einem nicht-Socket")
INPUT ("Socket type not supported")
OUTPUT ("Socket-Typ wird nicht unterstützt")
INPUT ("Software caused connection abort")
OUTPUT ("Das Programm verursachte den Abbruch der Verbindung")
INPUT ("Sorry. You are not root\n")
OUTPUT ("Sorry, diese Funktion kann nur vom Systemverwalter »root« durchgeführt werden.\n")
INPUT ("Source definitions are found in FILE")
OUTPUT ("Die Quell-Definitionen stehen in der Datei FILE")
INPUT ("Srmount error")
OUTPUT ("»Srmount«-Fehler")
INPUT ("Stack fault")
OUTPUT ("Stackfehler")
INPUT ("Stale NFS file handle")
OUTPUT ("Veraltete NFS-Dateizugriffsnummer")
INPUT ("Start NUMBER threads")
OUTPUT ("Starte die Anzahl NUMBER Threads")
INPUT ("Status            : %s\n")
OUTPUT ("Status            : %s\n")
INPUT ("Stopped")
OUTPUT ("Angehalten")
INPUT ("Stopped (signal)")
OUTPUT ("Angehalten (Signal)")
INPUT ("Stopped (tty input)")
OUTPUT ("Angehalten (tty-Eingabe)")
INPUT ("Stopped (tty output)")
OUTPUT ("Angehalten (tty-Ausgabe)")
INPUT ("Streams pipe error")
OUTPUT ("Fehler in Stream-Pipe")
INPUT ("Structure needs cleaning")
OUTPUT ("Die Struktur muß bereinigt werden")
INPUT ("Success")
OUTPUT ("Erfolg")
INPUT ("Suppress warnings and information messages")
OUTPUT ("Unterdrücke Warnungen und informative Nachrichten")
INPUT ("Symbolic character names defined in FILE")
OUTPUT ("Symbolische Namen für Zeichen sind in der Datei FILE definiert")
INPUT ("System error")
OUTPUT ("Systemfehler")
INPUT ("System information:")
OUTPUT ("System-Information:")
INPUT ("System resource allocation failure")
OUTPUT ("Fehler bei der Beschaffung einer Systemressource")
INPUT ("\
System's directory for character maps : %s\n\
                       repertoire maps: %s\n\
                       locale path    : %s\n\
%s")
OUTPUT ("\
System-Verzeichnis für character maps : %s\n\
                       repertoire maps: %s\n\
                       locale path    : %s\n\
%s")
INPUT ("TABLE")
OUTPUT ("TABELLE")
INPUT ("TABLE\n")
OUTPUT ("TABELLE\n")
INPUT ("TABLE,yes")
OUTPUT ("TABELLE,ja")
INPUT ("Table Type          : %s\n")
OUTPUT ("Tabellentyp         : %s\n")
INPUT ("Temporary failure in name resolution")
OUTPUT ("Temporärer Fehler bei der Namensauflösung")
INPUT ("Terminated")
OUTPUT ("Beendet")
INPUT ("Text file busy")
OUTPUT ("Das Programm kann nicht ausgeführt oder verändert werden (busy)")
INPUT ("\
The following list contain all the coded character sets known.  This does\n\
not necessarily mean that all combinations of these names can be used for\n\
the FROM and TO command line parameters.  One coded character set can be\n\
listed with several different names (aliases).\n\
  Some of the names are no plain strings but instead regular expressions and\n\
they match a variety of names which can be given as parameters to the\n\
program.\n\
\n\
  ")
OUTPUT ("\
Die folgende Liste enthält alle bekannten Zeichensatzkodierungen.  Das\n\
bedeutet nicht, daß zwischen allen Kombinationen dieser Namen als FROM\n\
und TO Parameter konvertiert werden kann.  Eine Zeichensatzkodierung kann\n\
unter verschiedenen Namen aufgeführt sein (sog. Aliasnamen).\n\
\n\
Einige Namen sind keine normalen Zeichenketten, sondern Reguläre Ausdrücke;\n\
diese passen zu einer Reihe von Namen, die als Parameter angegeben\n\
werden können.\n\
\n\
  ")
INPUT ("Time to live : ")
OUTPUT ("Time-to-Live : ")
INPUT ("Timer expired")
OUTPUT ("Der virtuelle Zeitnehmer ist abgelaufen")
INPUT ("Too many attributes")
OUTPUT ("Zu viele Attribute")
INPUT ("Too many levels of symbolic links")
OUTPUT ("Zu viele Ebenen aus symbolischen Links")
INPUT ("Too many links")
OUTPUT ("Zu viele Links")
INPUT ("Too many open files")
OUTPUT ("Zu viele offene Dateien")
INPUT ("Too many open files in system")
OUTPUT ("Zu viele offene Dateien im System")
INPUT ("Too many processes")
OUTPUT ("Zu viele Prozesse")
INPUT ("Too many references: cannot splice")
OUTPUT ("Zu viele Referenzen: can't splice")
INPUT ("Too many users")
OUTPUT ("Zu viele Benutzer")
INPUT ("Trace/breakpoint trap")
OUTPUT ("Trace/Breakpoint ausgelöst")
INPUT ("Trailing backslash")
OUTPUT ("Angehängter Backslash (»\\«)")
INPUT ("Translator died")
OUTPUT ("Der Übersetzer ist gestorben")
INPUT ("Transport endpoint is already connected")
OUTPUT ("Der Socket ist bereits verbunden")
INPUT ("Transport endpoint is not connected")
OUTPUT ("Der Socket ist nicht verbunden")
INPUT ("Try `%s --help' or `%s --usage' for more information.\n")
OUTPUT ("»%s --help« oder »%s --usage« gibt weitere Informationen.\n")
INPUT ("Trying %s...\n")
OUTPUT ("Versuche »%s«...\n")
INPUT ("Type : %s\n")
OUTPUT ("Typ : %s\n")
INPUT ("UNKNOWN")
OUTPUT ("UNBEKANNT")
INPUT ("Unable to authenticate NIS+ client")
OUTPUT ("Die Echtheit des NIS+-Clients kann nicht geprüft werden")
INPUT ("Unable to authenticate NIS+ server")
OUTPUT ("Die Echtheit des NIS+-Servers kann nicht geprüft werden")
INPUT ("Unable to create callback")
OUTPUT ("Die Callback-Prozedur kann nicht erstellt werden")
INPUT ("Unable to create process on server")
OUTPUT ("Es kann kein Prozeß auf dem Server gestartet werden")
INPUT ("Unknown (type = %d, bits = %d)\n")
OUTPUT ("Unbekannt (Typ = %d, Bits = %d)\n")
INPUT ("Unknown .netrc keyword %s")
OUTPUT ("Unbekanntes Schlüsselwort »%s« in der Datei ».netrc«")
INPUT ("Unknown NIS error code")
OUTPUT ("Unbekannter NIS-Fehlercode")
INPUT ("Unknown database: %s\n")
OUTPUT ("Unbekannte Datenbank: %s\n")
INPUT ("Unknown error")
OUTPUT ("Unbekannter Fehler")
INPUT ("Unknown error ")
OUTPUT ("Unbekannter Fehler ")
INPUT ("Unknown host")
OUTPUT ("Unbekannter Rechner")
INPUT ("Unknown object")
OUTPUT ("Unbekanntes Objekt")
INPUT ("Unknown option: %s %s %s")
OUTPUT ("Unbekannte Option: %s %s %s")
INPUT ("Unknown resolver error")
OUTPUT ("Unbekannter Fehler des »Resolvers«")
INPUT ("Unknown server error")
OUTPUT ("Unbekannter Fehler des Servers")
INPUT ("Unknown signal %d")
OUTPUT ("Unbekanntes Signal %d")
INPUT ("Unknown system error")
OUTPUT ("Unbekannter Systemfehler")
INPUT ("Unknown ypbind error")
OUTPUT ("Unbekannter Fehler im »ypbind«")
INPUT ("Unmatched ( or \\(")
OUTPUT ("»(« oder »\\(« ohne schließende Klammer")
INPUT ("Unmatched ) or \\)")
OUTPUT ("»)« oder »\\)« ohne öffnende Klammer")
INPUT ("Unmatched [ or [^")
OUTPUT ("»[« oder »[^« ohne schließende Klammer")
INPUT ("Unmatched \\{")
OUTPUT ("»\\{« ohne schließende Klammer")
INPUT ("Unrecognized variable `%s'")
OUTPUT ("Unbekannte Variable »%s«")
INPUT ("Urgent I/O condition")
OUTPUT ("Dringende Ein-/Ausgabebedingung")
INPUT ("Usage:")
OUTPUT ("Syntax:")
INPUT ("Usage: %s variable_name [pathname]\n")
OUTPUT ("Syntax: %s Variablenname [Pfadname]\n")
INPUT ("Usage: rpcinfo [ -n portnum ] -u host prognum [ versnum ]\n")
OUTPUT ("Syntax: rpcinfo [ -n Portnummer ] -u Rechner Programmnummer [ Versionsnummer ]\n")
INPUT ("Use separate cache for each user")
OUTPUT ("Verwende für jeden Benutzer einen eigenen Cache")
INPUT ("User defined signal 1")
OUTPUT ("Benutzerdefiniertes Signal 1")
INPUT ("User defined signal 2")
OUTPUT ("Benutzerdefiniertes Signal 2")
INPUT ("Value too large for defined data type")
OUTPUT ("Der Wert ist zu groß für den definierten Datentyp")
INPUT ("Virtual timer expired")
OUTPUT ("Der virtuelle Zeitnehmer ist abgelaufen")
INPUT ("Wild result from command execution")
OUTPUT ("Wildes Ergebnis aus der Kommandoausführung")
INPUT ("Window changed")
OUTPUT ("Die Fenstergröße wurde verändert")
INPUT ("Write names of available charmaps")
OUTPUT ("Gibt die Namen der verfügbaren »charmaps« aus")
INPUT ("Write names of available locales")
OUTPUT ("Gibt die Namen der verfügbaren Lokalen aus")
INPUT ("Write names of selected categories")
OUTPUT ("Gibt die Namen der ausgewählten Kategorien aus")
INPUT ("Write names of selected keywords")
OUTPUT ("Gibt die Namen der ausgewählten Schlüsselwörter aus")
INPUT ("Write output to file NAME")
OUTPUT ("Schreibe die Ausgabe in die Datei NAME")
INPUT ("Written by %s.\n")
OUTPUT ("Implementiert von %s.\n")
INPUT ("Wrong medium type")
OUTPUT ("Falscher Medien-Typ")
INPUT ("X500")
OUTPUT ("X500")
INPUT ("XCHS")
OUTPUT ("XCHS")
INPUT ("YPBINDPROC_DOMAIN: %s\n")
OUTPUT ("YPBINDPROC_DOMAIN: %s\n")
INPUT ("Yes, 42 is the meaning of life")
OUTPUT ("Ja, 42 ist die Antwort auf die Frage nach dem Leben, dem Sein und allem sonst")
INPUT ("You really blew it this time")
OUTPUT ("Diesmal hast Du es wirklich kaputtgemacht")
INPUT ("Zone continuation line end time is not after end time of previous line")
OUTPUT ("Die Ende-Zeit der Fortsetzungszeile ist nicht später als die Ende-Zeit der vorangegangenen Zeile")
INPUT ("[FILE...]")
OUTPUT ("[Datei...]")
INPUT ("__get_myaddress: ioctl (get interface configuration)")
OUTPUT ("__get_myaddress: ioctl (Holen der Schnittstellen-Konfiguration)")
INPUT ("`%1$s' definition does not end with `END %1$s'")
OUTPUT ("Die Definition von »%1$s« ist nicht durch »END %1$s« abgeschlossen")
INPUT ("`%s' is no correct profile data file for `%s'")
OUTPUT ("»%s« ist keine gültige Profiledaten-Datei für »%s«")
INPUT ("`-1' must be last entry in `%s' field in `%s' category")
OUTPUT ("»-1« muß der letzte Eintrag im »%s«-Feld der »%s«-Kategorie sein")
INPUT ("`...' must only be used in `...' and `UNDEFINED' entries")
OUTPUT ("»...« darf nur in »...« und »UNDEFINED«-Einträgen verwendet werden")
INPUT ("`from' expected after first argument to `collating-element'")
OUTPUT ("»from« wird nach dem ersten Argument von »collating-element«  erwartet")
INPUT ("`from' string in collation element declaration contains unknown character")
OUTPUT ("Der »from«-String in der Deklaration des Sortierelements enthält unbekannte Zeichen")
INPUT ("ai_family not supported")
OUTPUT ("»ai_family« wird nicht unterstützt")
INPUT ("ai_socktype not supported")
OUTPUT ("»ai_family« wird nicht unterstützt")
INPUT ("already running")
OUTPUT ("ist bereits gestartet")
INPUT ("argument to <%s> must be a single character")
OUTPUT ("Das Argument für »<%s>« muß ein einzelnes Zeichen sein")
INPUT ("argument to `%s' must be a single character")
OUTPUT ("Das Argument zu »%s« muß ein einzelnes Zeichen sein")
INPUT ("auth_none.c - Fatal marshalling problem")
OUTPUT ("auth_none.c - Fatales »marshalling«-Problem")
INPUT ("authunix_create: out of memory\n")
OUTPUT ("authunix_create: Hauptspeicher erschöpft\n")
INPUT ("bad argument")
OUTPUT ("Das Argument ist ungültig")
INPUT ("bad owner")
OUTPUT ("Ungültiger Eigentümer")
INPUT ("blank FROM field on Link line")
OUTPUT ("Leeres FROM-Feld in der Link-Zeile")
INPUT ("blank TO field on Link line")
OUTPUT ("Leeres TO-Feld in der Link-Zeile")
INPUT ("block freed twice\n")
OUTPUT ("Speicherblock zum zweiten Mal freigegeben\n")
INPUT ("bogus mcheck_status, library is buggy\n")
OUTPUT ("Eigenartiger »mcheck_status«, die Bibliothek enthält Fehler\n")
INPUT ("broadcast: ioctl (get interface configuration)")
OUTPUT ("Broadcast: ioctl (Holen der Konfiguration der Schnittstelle)")
INPUT ("broadcast: ioctl (get interface flags)")
OUTPUT ("Broadcast: ioctl (Holen der Parameter der Schnittstelle)")
INPUT ("buffer overflow")
OUTPUT ("Pufferüberlauf")
INPUT ("cache_set: could not allocate new rpc_buffer")
OUTPUT ("cache_set: Kann keinen neuen RPC-Puffer »rcp_buffer« anlegen")
INPUT ("cache_set: victim alloc failed")
OUTPUT ("cache_set: Das Opfer wurde nicht alloziert")
INPUT ("cache_set: victim not found")
OUTPUT ("cache_set: Das Opfer wurde nicht gefunden")
INPUT ("can't determine time zone abbreviation to use just after until time")
OUTPUT ("Kann die Abkürzung der Zeitzone zur Verwendung direkt nach der Ende-Zeit nicht bestimmen")
INPUT ("can't reassign procedure number %d\n")
OUTPUT ("Kann die Nummer der Prozedur %d nicht erneut zuweisen\n")
INPUT ("cannot `stat' locale file `%s'")
OUTPUT ("Kann den Status der Lokale-Datei »%s« nicht bestimmen")
INPUT ("cannot allocate symbol data")
OUTPUT ("Nicht genügend Hauptspeicher für Symboldaten verfügbar")
INPUT ("cannot create internal descriptor")
OUTPUT ("Kann keinen internen Deskriptor erzeugen")
INPUT ("cannot create internal descriptors")
OUTPUT ("Kann keine internen Deskriptoren erzeugen")
INPUT ("cannot enable socket to accept connections: %s")
OUTPUT ("Der Socket kann nicht zum Annehmen von Verbindungen aktiviert werden: %s")
INPUT ("cannot find C preprocessor: %s \n")
OUTPUT ("Kann den C Präprozessor nicht finden: %s \n")
INPUT ("cannot find any C preprocessor (cpp)\n")
OUTPUT ("Kann keinen C Präprozessor finden (cpp)\n")
INPUT ("cannot handle old request version %d; current version is %d")
OUTPUT ("Kann die alte Version %d nicht verarbeiten; aktuelle Version ist %d")
INPUT ("cannot insert collation element `%.*s'")
OUTPUT ("Kann das Sortierelement »%.*s« nicht einfügen")
INPUT ("cannot insert into result table")
OUTPUT ("Kann nicht in die Ergebnistabelle einfügen")
INPUT ("cannot insert new collating symbol definition: %s")
OUTPUT ("Kann die neue Sortiersymboldefinition nicht einfügen: %s")
INPUT ("cannot load profiling data")
OUTPUT ("Kann die Profiling-Daten nicht laden")
INPUT ("cannot open")
OUTPUT ("Öffnen fehlgeschlagen")
INPUT ("cannot open `%s'")
OUTPUT ("Öffnen von »%s« fehlgeschlagen")
INPUT ("cannot open database file `%s': %s")
OUTPUT ("Kann die Ausgabedatei »%s« nicht öffnen: %s")
INPUT ("cannot open input file `%s'")
OUTPUT ("Kann die Eingabedatei »%s« nicht öffnen")
INPUT ("cannot open locale definition file `%s'")
OUTPUT ("Kann die Lokale-Definitionsdatei »%s« nicht öffnen")
INPUT ("cannot open output file")
OUTPUT ("Kann die Ausgabedatei nicht öffnen")
INPUT ("cannot open output file `%s'")
OUTPUT ("Kann die Ausgabedatei »%s« nicht öffnen")
INPUT ("cannot open output file `%s' for category `%s'")
OUTPUT ("Kann die Ausgabedatei »%s« für die Kategorie »%s« nicht öffnen")
INPUT ("cannot open socket: %s")
OUTPUT ("Kann den Socket nicht öffnen: %s")
INPUT ("cannot process order specification")
OUTPUT ("Kann die Spezifikation der Sortierreihenfolge nicht verarbeiten")
INPUT ("cannot read character map directory `%s'")
OUTPUT ("Das Verzeichnis »%s« der Zeichensatz-Definitionen kann nicht gelesen werden")
INPUT ("cannot read configuration file; this is fatal")
OUTPUT ("Kann die Konfigurationsdatei nicht lesen; das ist fatal")
INPUT ("cannot read from client")
OUTPUT ("Kann nicht vom Client lesen")
INPUT ("cannot read header from `%s'")
OUTPUT ("Kann den Header von »%s« nicht lesen")
INPUT ("cannot read locale directory `%s'")
OUTPUT ("Kann das Lokale-Verzeichnis »%s« nicht lesen")
INPUT ("cannot read locale file `%s'")
OUTPUT ("Kann die Lokale-Datei »%s« nicht lesen")
INPUT ("cannot read repertoire map `%s'")
OUTPUT ("Kann die »repertoire«-Map »%s« nicht lesen")
INPUT ("cannot read statistics data")
OUTPUT ("Kann keine Statistikdaten lesen")
INPUT ("cannot stat() file `%s': %s")
OUTPUT ("Kann den Status (stat()) der Datei »%s« nicht lesen: %s")
INPUT ("cannot write output files to `%s'")
OUTPUT ("Kann die Ausgabedatei »%s« nicht schreiben")
INPUT ("cannot write result: %s")
OUTPUT ("Kann das Ergebnis nicht schreiben: %s")
INPUT ("cannot write statistics: %s")
OUTPUT ("Kann die Statistik nicht schreiben: %s")
INPUT ("cannot write to client")
OUTPUT ("Kann nicht zum Client schreiben")
INPUT ("category data requested more than once: should not happen")
OUTPUT ("Die Daten einer Kategorie sind mehrfach angefordert worden, das sollte nicht passieren")
INPUT ("character '%s' in class `%s' must be in class `%s'")
OUTPUT ("Das Zeichen »%s«, das in der Zeichenklasse »%s« enthalten ist, muß auch in der Zeichenklasse »%s« enthalten sein")
INPUT ("character '%s' in class `%s' must not be in class `%s'")
OUTPUT ("Das Zeichen »%s« in der Zeichenklasse »%s« darf nicht in der Zeichenklasse »%s« enthalten sein")
INPUT ("character <SP> not defined in character map")
OUTPUT ("Das Zeichen »<SP>« ist in der Zeichen-Definition nicht enthalten")
INPUT ("character L'%s' (index %Zd) in class `%s' must be in class `%s'")
OUTPUT ("Das Zeichen L»%s« (Index %Zd), das in der Zeichenklasse »%s« enthalten ist, muß auch in der Zeichenklasse »%s« enthalten sein")
INPUT ("character L'%s' (index %Zd) in class `%s' must not be in class `%s'")
OUTPUT ("Das Zeichen L»%s« (Index %Zd) in der Zeichenklasse »%s« darf nicht in der Zeichenklasse »%s« enthalten sein")
INPUT ("character `%s' not defined while needed as default value")
OUTPUT ("Das Zeichen »%s« ist nicht definiert, wird aber als Vorgabewert benötigt")
INPUT ("character class `%s' already defined")
OUTPUT ("Die Zeichenklasse »%s« ist bereits definiert")
INPUT ("character map `%s' already defined")
OUTPUT ("Die Zeichensatzbeschreibung »%s« ist bereits definiert")
INPUT ("character map file `%s' not found")
OUTPUT ("Die Zeichensatzbeschreibungsdatei »%s« wurde nicht gefunden")
INPUT ("clnt_raw.c - Fatal header serialization error.")
OUTPUT ("clnt_raw.c - Fataler Fehler bei der Header-Serialisierung.")
INPUT ("clnttcp_create: out of memory\n")
OUTPUT ("clnttcp_create: Hauptspeicher erschöpft\n")
INPUT ("clntudp_create: out of memory\n")
OUTPUT ("clntudp_create: Hauptspeicher erschöpft\n")
INPUT ("clntunix_create: out of memory\n")
OUTPUT ("clntunix_create: Hauptspeicher erschöpft\n")
INPUT ("collation element `%.*s' appears more than once: ignore line")
OUTPUT ("Das Sortierungselement »%.*s« ist mehr als einmal angegeben: Die Zeile wird ignoriert")
INPUT ("collation symbol `%.*s' appears more than once: ignore line")
OUTPUT ("Das Sortierungssymbol »%.*s« ist mehr als einmal angegeben; die Zeile wird ignoriert")
INPUT ("collation symbol expected after `%s'")
OUTPUT ("Nach »%s« wird ein Sortierungssymbol erwartet")
INPUT ("connect to address %s: ")
OUTPUT ("Verbindungsaufbau zur Adresse %s: ")
INPUT ("constant or identifier expected")
OUTPUT ("Konstante oder Bezeichner erwartet")
INPUT ("conversion from `%s' to `%s' not supported")
OUTPUT ("Konvertierung von »%s« nach »%s« wird nicht unterstützt")
INPUT ("conversion stopped due to problem in writing the output")
OUTPUT ("Die Konvertierung wurde wegen Problemen bei der Ausgabe beendet")
INPUT ("couldn't create an rpc server\n")
OUTPUT ("Kann keinen RPC-Server erzeugen\n")
INPUT ("couldn't register prog %d vers %d\n")
OUTPUT ("Kann das Programm »%d« Version »%d« nicht registrieren\n")
INPUT ("database [key ...]")
OUTPUT ("Datenbank [Schlüssel ...]")
INPUT ("default character map file `%s' not found")
OUTPUT ("Die Default-Zeichensatzbeschreibung in der Datei »%s« wurde nicht gefunden")
INPUT ("direction flag in string %d in `era' field in category `%s' is not '+' nor '-'")
OUTPUT ("Der Richtungsanzeiger in der Zeichenkette %d im »era«-Feld in der Kategorie »%s« ist weder »+« noch »-«")
INPUT ("direction flag in string %d in `era' field in category `%s' is not a single character")
OUTPUT ("Der Richtungsanzeiger in der Zeichenkette %d im »era«-Feld in der Kategorie »%s« ist kein einzelnes Zeichen")
INPUT ("duplicate character name `%s'")
OUTPUT ("Der Name des Zeichens »%s« ist mehrfach angegeben")
INPUT ("duplicate collating element definition")
OUTPUT ("Mehrfache Definition des Sortierungselementes")
INPUT ("duplicate definition for character `%.*s'")
OUTPUT ("Mehrfache Definition des Eintrages »%.*s«")
INPUT ("duplicate key")
OUTPUT ("Doppelter Schlüssel")
INPUT ("duplicate set definition")
OUTPUT ("Doppelte »set«-Definition")
INPUT ("duplicate zone name %s (file \"%s\", line %d)")
OUTPUT ("Doppelter Zonenname »%s« (Datei »%s«, Zeile %d)")
INPUT ("duplicated message identifier")
OUTPUT ("Der Nachrichtenbezeichner ist mehrfach vorhanden")
INPUT ("duplicated message number")
OUTPUT ("Die Nachrichtennummer ist mehrfach vorhanden")
INPUT ("empty char string")
OUTPUT ("Leere Zeichenkette")
INPUT ("empty weight name: line ignored")
OUTPUT ("Leerer Name des Sortiergewichtes: Die Zeile wird ignoriert")
INPUT ("enablecache: cache already enabled")
OUTPUT ("enablecache: Cache ist bereits aktiv")
INPUT ("enablecache: could not allocate cache")
OUTPUT ("enablecache: Kann keinen Cache anlegen")
INPUT ("enablecache: could not allocate cache data")
OUTPUT ("enablecache: Kann die Cache-Daten nicht anlegen")
INPUT ("enablecache: could not allocate cache fifo")
OUTPUT ("enablecache: Kann keinen FIFO-Cache anlegen")
INPUT ("encoding for output")
OUTPUT ("Kodierung für die Ausgabe")
INPUT ("encoding of original text")
OUTPUT ("Kodierung für den ursprünglichen Text")
INPUT ("end point of ellipsis range is bigger then start")
OUTPUT ("Das Ende eines Auslassungsintervalls ist größer als der Start")
INPUT ("error getting callers id: %s")
OUTPUT ("Fehler beim Feststellen der Identität des Aufrufers: %s")
INPUT ("error while closing input `%s'")
OUTPUT ("Fehler beim Schließen der Eingabedatei »%s«")
INPUT ("error while closing output file")
OUTPUT ("Fehler beim Schließen der Ausgabedatei ")
INPUT ("error while closing the profiling data file")
OUTPUT ("Fehler beim Schließen der Datei mit den Profiling-Daten")
INPUT ("error while inserting collation element into hash table")
OUTPUT ("Fehler beim Einfügen des Sortierelementes in die Hash-Tabelle")
INPUT ("error while inserting to hash table")
OUTPUT ("Fehler beim Einfügen in die Hash-Tabelle")
INPUT ("error while reading the input")
OUTPUT ("Fehler beim Lesen der Eingabe")
INPUT ("expect string argument for `copy'")
OUTPUT ("Für »copy« wird ein String-Argument erwartet")
INPUT ("expected continuation line not found")
OUTPUT ("Die erwartete Fortsetzungszeile ist nicht vorhanden")
INPUT ("failed to load shared object `%s'")
OUTPUT ("Fehler beim Laden des Shared Objects »%s«")
INPUT ("failed to load symbol data")
OUTPUT ("Fehler beim Laden der Symboldaten")
INPUT ("failed to mmap the profiling data file")
OUTPUT ("Fehler beim »mmap« der Datei mit den Profiling-Daten")
INPUT ("failed to start conversion processing")
OUTPUT ("Fehler beim Start der Konvertierung")
INPUT ("failure while writing data for category `%s'")
OUTPUT ("Fehler beim Schreiben der Daten für die Kategorie »%s«")
INPUT ("fcntl: F_SETFD")
OUTPUT ("fcntl: F_SETFD")
INPUT ("field `%s' in category `%s' undefined")
OUTPUT ("Der Eintrag »%s« in der Kategorie »%s« ist nicht definiert")
INPUT ("file `%s' already exists and may be overwritten\n")
OUTPUT ("Die Datei »%s« existiert bereits und würde überschrieben\n")
INPUT ("from-value of `collating-element' must be a string")
OUTPUT ("Der »From«-Wert eines Sortierelementes muß eine Zeichenkette sein")
INPUT ("fstat failed")
OUTPUT ("Fehler beim Holen des Datei-Status mit »fstat«")
INPUT ("garbage at end of character code specification")
OUTPUT ("Murks am Ende einer Zeichensatzspezifikation")
INPUT ("garbage at end of number")
OUTPUT ("Am Ende der Zahl sind unsinnige Einträge")
INPUT ("garbage at end of offset value in string %d in `era' field in category `%s'")
OUTPUT ("Unsinnige Einträge am Ende des Offset-Wertes in der Zeichenkette %d im »era«-Feld der Kategorie »%s«")
INPUT ("garbage at end of starting date in string %d in `era' field in category `%s'")
OUTPUT ("Unsinnige Einträge am Ende des Start-Datums in der Zeichenkette %d im »era«-Feld der Kategorie »%s«")
INPUT ("garbage at end of stopping date in string %d in `era' field in category `%s'")
OUTPUT ("Unsinnige Eintrage am Ende des Stop-Datums in der Zeichenkette %d im »era«-Feld der Kategorie »%s«")
INPUT ("generate call graph")
OUTPUT ("Erzeuge einen Aufruf-Graphen")
INPUT ("generate flat profile with counts and ticks")
OUTPUT ("Erzeuge ein 'flaches' Profile mit Aufrufzahlen und -zeiten")
INPUT ("get_myaddress: ioctl (get interface configuration)")
OUTPUT ("get_myaddress: ioctl (Holen der Schnittstellen-Konfiguration)")
INPUT ("getent - get entries from administrative database.")
OUTPUT ("getent - lese Einträge aus administrativen Datenbanken.")
INPUT ("handle_request: request received (Version = %d)")
OUTPUT ("handle_request: Anforderung empfangen (Version = %d)")
INPUT ("hard link failed, symbolic link used")
OUTPUT ("Hardlink fehlgeschlagen, es wird ein symbolischer Link verwendet")
INPUT ("hard linked somewhere")
OUTPUT ("Ist irgendwo ein Hard-Link")
INPUT ("illegal CORRECTION field on Leap line")
OUTPUT ("ungültiges »CORRECTION«-Feld in der »Leap«-Zeile")
INPUT ("illegal Rolling/Stationary field on Leap line")
OUTPUT ("ungültiges »Rolling/Stationary«-Feld in der »Leap«-Zeile")
INPUT ("illegal character constant in string")
OUTPUT ("Ungültige Zeichenkonstante in der Zeichenkette")
INPUT ("illegal character in file: ")
OUTPUT ("Ungültiges Zeichen in der Datei: ")
INPUT ("illegal collation element")
OUTPUT ("Ungültiges Sortierelement")
INPUT ("illegal definition")
OUTPUT ("Ungültige Definition")
INPUT ("illegal encoding given")
OUTPUT ("Ungültige Kodierung angegeben")
INPUT ("illegal escape sequence at end of string")
OUTPUT ("ungültige Escape-Sequenz am Ende der Zeichenkette")
INPUT ("illegal input sequence at position %ld")
OUTPUT ("ungültige Eingabe-Sequenz an der Stelle %ld")
INPUT ("illegal names for character range")
OUTPUT ("ungültige Namen für den Zeichenbereich")
INPUT ("illegal nettype :`%s'\n")
OUTPUT ("ungültiger nettype : »%s«\n")
INPUT ("illegal number for offset in string %d in `era' field in category `%s'")
OUTPUT ("ungültige Nummer für den Offset in der Zeichenkette %d im »era«-Feld in der Kategorie »%s«")
INPUT ("illegal set number")
OUTPUT ("ungültige »set«-Nummer")
INPUT ("illegal starting date in string %d in `era' field in category `%s'")
OUTPUT ("ungültiges Start-Datum in der Zeichenkette %d im »era«-Feld in der Kategorie »%s«")
INPUT ("illegal stopping date in string %d in `era' field in category `%s'")
OUTPUT ("ungültiges Ende-Datum in der Zeichenkette %d im »era«-Feld in der Kategorie »%s«")
INPUT ("implementation limit: no more than %d character classes allowed")
OUTPUT ("Limit der Implementation: Es sind nicht mehr als %d Zeichen-Klassen erlaubt")
INPUT ("implementation limit: no more than %d character maps allowed")
OUTPUT ("Limit der Implementation: Es sind nicht mehr als %d Zeichen-Maps erlaubt")
INPUT ("incomplete character or shift sequence at end of buffer")
OUTPUT ("unvollständige Zeichen- oder Shift-Folge am Ende des Puffers")
INPUT ("incorrectly formatted file")
OUTPUT ("ungültig formatierte Datei")
INPUT ("input line of unknown type")
OUTPUT ("Die Eingabezeile ist von einem unbekannten Typ")
INPUT ("internal error (illegal descriptor)")
OUTPUT ("interner Fehler (ungültiger Descriptor)")
INPUT ("internal error - addtype called with bad isdst")
OUTPUT ("Interner Fehler - »addtype« wurde mit einer ungültigen »isdst« aufgerufen")
INPUT ("internal error - addtype called with bad ttisgmt")
OUTPUT ("Interner Fehler - »addtype« wurde mit einem ungültigen »ttisgmt« aufgerufen")
INPUT ("internal error - addtype called with bad ttisstd")
OUTPUT ("Interner Fehler - »addtype« wurde mit einem ungültigen »ttisstd« aufgerufen")
INPUT ("internal error in %s, line %u")
OUTPUT ("Interner Fehler in der Datei »%s«, Zeile %u")
INPUT ("invalid UTC offset")
OUTPUT ("ungültiger UTC-Offset")
INPUT ("invalid abbreviation format")
OUTPUT ("ungültiges Abkürzungsformat")
INPUT ("invalid day of month")
OUTPUT ("Ungültiger Tag des Monats")
INPUT ("invalid ending year")
OUTPUT ("Ungültiges Ende-Jahr")
INPUT ("invalid leaping year")
OUTPUT ("Ungültiges Schaltjahr")
INPUT ("invalid mode for dlopen()")
OUTPUT ("Ungültiger Mode für dlopen()")
INPUT ("invalid month name")
OUTPUT ("ungültiger Monatsname")
INPUT ("invalid saved time")
OUTPUT ("Ungültige gespeicherte Zeit")
INPUT ("invalid starting year")
OUTPUT ("Ungültiges Anfangsjahr")
INPUT ("invalid time of day")
OUTPUT ("Ungültige Tageszeit")
INPUT ("invalid weekday name")
OUTPUT ("ungültiger Name für einen Wochentag")
INPUT ("key length in request too long: %Zd")
OUTPUT ("Die Schlüssellänge in der Anforderung ist zu lang: %Zd")
INPUT ("line after ellipsis must contain character definition")
OUTPUT ("Die Zeile nach einem Auslassungintervall muß eine Zeichen-Definition enthalten")
INPUT ("line before ellipsis does not contain definition for character constant")
OUTPUT ("Die Zeile vor einem Auslassungsintervall muß eine Zeichen-Konstante enthalten")
INPUT ("line too long")
OUTPUT ("Die Zeile ist zu lang")
INPUT ("list all known coded character sets")
OUTPUT ("Gib alle bekannten Zeichensatz-Kodierungen aus")
INPUT ("locale file `%s', used in `copy' statement, not found")
OUTPUT ("Die Lokale-Datei »%s«, die im »copy«-Befehl verwendet wird, ist nicht vorhanden")
INPUT ("lstat failed")
OUTPUT ("Fehler beim Holen des Link-Status mit »lstat«")
INPUT ("malformed line ignored")
OUTPUT ("ungültige Eingabezeile ignoriert")
INPUT ("mapping of section header string table failed")
OUTPUT ("Das Mappen der Section-Header String-Tabelle ist fehlgeschlagen")
INPUT ("mapping of section headers failed")
OUTPUT ("Das Mapping der Section-Headers ist fehlgeschlagen")
INPUT ("memory clobbered before allocated block\n")
OUTPUT ("Der Speicher vor dem allozierten Block wurde überschrieben\n")
INPUT ("memory clobbered past end of allocated block\n")
OUTPUT ("Der Speicher nach dem Ende des allozierten Blockes wurde überschrieben\n")
INPUT ("memory exhausted")
OUTPUT ("Kein Hauptspeicher mehr verfügbar")
INPUT ("memory is consistent, library is buggy\n")
OUTPUT ("Die Speicherverwaltung ist konsistent, die Bibliothek enthält Fehler\n")
INPUT ("missing era format in string %d in `era' field in category `%s'")
OUTPUT ("fehlendes »era«-Format in der Zeichenkette %d im »era«-Feld in der Kategorie »%s«")
INPUT ("missing era name in string %d in `era' field in category `%s'")
OUTPUT ("fehlender »era«-Name in der Zeichenkette %d im »era« Feld in der Kategorie »%s«")
INPUT ("nameless rule")
OUTPUT ("Regel ohne Name")
INPUT ("neither original nor target encoding specified")
OUTPUT ("Weder die ursprüngliche noch die Ziel-Kodierung angegeben")
INPUT ("netname2user: (nis+ lookup): %s\n")
OUTPUT ("netname2user: (NIS+ Lookup): %s\n")
INPUT ("netname2user: DES entry for %s in directory %s not unique")
OUTPUT ("netname2user: DES Eintrag für »%s« im Verzeichnis »%s« ist nicht eindeutig")
INPUT ("netname2user: LOCAL entry for %s in directory %s not unique")
OUTPUT ("netname2user: LOCAL Eintrag für »%s« im Verzeichnis »%s« ist nicht eindeutig")
INPUT ("netname2user: missing group id list in `%s'.")
OUTPUT ("netname2user: fehlende Group-ID Liste in »%s«.")
INPUT ("netname2user: principal name `%s' too long")
OUTPUT ("netname2user: der Principal-Name »%s« ist zu lang")
INPUT ("netname2user: should not have uid 0")
OUTPUT ("netname2user: sollte nicht die Benutzernummer 0 haben")
INPUT ("never registered prog %d\n")
OUTPUT ("Das Programm %d wurde nie registriert\n")
INPUT ("no <Uxxxx> or <Uxxxxxxxx> value given")
OUTPUT ("Kein <Uxxxx> oder <Uxxxxxxxx> Wert angegeben")
INPUT ("no correct regular expression for field `%s' in category `%s': %s")
OUTPUT ("Kein gültiger regulärer Ausdruck für den Eintrag »%s« in der Kategorie »%s«: %s")
INPUT ("no day in month matches rule")
OUTPUT ("Kein Tag des Monats paßt zur angegebenen Regel")
INPUT ("no definition of `UNDEFINED'")
OUTPUT ("Keine Definition für »UNDEFINED«")
INPUT ("no filename for profiling data given and shared object `%s' has no soname")
OUTPUT ("Kein Dateiname für Profiling-Datenn angegeben und das Shared Object »%s« hat keinen »soname«")
INPUT ("no other keyword shall be specified when `copy' is used")
OUTPUT ("Es dürfen keine anderen Schlüsselworte angegeben werden, wenn »copy« verwendet wird")
INPUT ("no output file produced because warning were issued")
OUTPUT ("Es wurde keine Ausgabedatei erzeugt, weil Warnungen ausgegeben wurden")
INPUT ("no repertoire map specified: cannot proceed")
OUTPUT ("keine »repertoire«-Map angegeben: Verarbeitung abgebrochen")
INPUT ("no symbolic name given")
OUTPUT ("Kein symbolischer Name angegeben")
INPUT ("no symbolic name given for end of range")
OUTPUT ("Kein symbolischer Name für das Ende des Intervalles angegeben")
INPUT ("no weight defined for symbol `%s'")
OUTPUT ("Kein Sortiergewicht (»Weight«) für das Symbol »%s« definiert")
INPUT ("not regular file")
OUTPUT ("Keine reguläre Datei")
INPUT ("\
nscd configuration:\n\
\n\
%15d  server debug level\n")
OUTPUT ("\
nscd Konfiguration:\n\
\n\
%15d  Server Debug Level\n")
INPUT ("nscd not running!\n")
OUTPUT ("nscd läuft nicht!\n")
INPUT ("only WIDTH definitions are allowed to follow the CHARMAP definition")
OUTPUT ("Nur »WIDTH«-Definitionen dürfen nach einer »CHARMAP«-Definition folgen")
INPUT ("original encoding not specified using `-f'")
OUTPUT ("Die ursprüngliche Kodierung nicht mit »-f« angegeben")
INPUT ("output file")
OUTPUT ("Ausgabedatei")
INPUT ("pmap_getmaps rpc problem")
OUTPUT ("pmap_getmaps RPC Problem")
INPUT ("poll: protocol failure in circuit setup\n")
OUTPUT ("poll: Protokollfehler im Verbindungsaufbau\n")
INPUT ("preprocessor error")
OUTPUT ("Fehler beim Aufruf des Präprozessors")
INPUT ("print list of count paths and their number of use")
OUTPUT ("Gib eine Liste der gezählten Pfade und der Anzahl der Benutzung aus")
INPUT ("print progress information")
OUTPUT ("Gib Informationen über den Bearbeitungsstand aus")
INPUT ("problems while reading `%s'")
OUTPUT ("Probleme beim Lesen von »%s«")
INPUT ("profiling data file `%s' does not match shared object `%s'")
OUTPUT ("Die Datei »%s« mit Profiling-Daten paßt nicht zum Shared Object »%s«")
INPUT ("program %lu is not available\n")
OUTPUT ("Das Programm %lu ist nicht verfügbar\n")
INPUT ("program %lu version %lu is not available\n")
OUTPUT ("Das Programm %lu ist in der Version %lu nicht verfügbar\n")
INPUT ("program %lu version %lu ready and waiting\n")
OUTPUT ("Program %lu Version %lu ist bereit und wartet\n")
INPUT ("rcmd: poll (setting up stderr): %m\n")
OUTPUT ("rcmd: poll (Vorbereiten der Standardfehlerausgabe): %m\n")
INPUT ("rcmd: socket: All ports in use\n")
OUTPUT ("rcmd: Socket: Alle Ports sind zur Zeit belegt\n")
INPUT ("rcmd: write (setting up stderr): %m\n")
OUTPUT ("rcmd: write (Vorbereiten der Standardfehlerausgabe): %m\n")
INPUT ("registerrpc: out of memory\n")
OUTPUT ("registerrpc: Hauptspeicher erschöpft\n")
INPUT ("repeated leap second moment")
OUTPUT ("Wiederholung der »Leap«-Sekunde")
INPUT ("repertoire map file `%s' not found")
OUTPUT ("Die »repertoire« Map-Datei »%s« wurde nicht gefunden")
INPUT ("rpcgen: arglist coding error\n")
OUTPUT ("rpcgen: Kodierungsfehler bei der »arglist«\n")
INPUT ("rpcgen: too many defines\n")
OUTPUT ("rpcgen: Zu viele Defines\n")
INPUT ("rpcinfo: %s is unknown host\n")
OUTPUT ("rpcinfo: »%s« ist ein unbekannter Rechner\n")
INPUT ("rpcinfo: %s is unknown service\n")
OUTPUT ("rpcinfo: »%s« ist ein unbekannter Service\n")
INPUT ("rpcinfo: Could not delete registration for prog %s version %s\n")
OUTPUT ("rpcinfo; Kann die Registrierung des Programms »%s« Version »%s« nicht löschen\n")
INPUT ("rpcinfo: broadcast failed: %s\n")
OUTPUT ("rpcinfo: Broadcast ist fehlgeschlagen: %s\n")
INPUT ("rpcinfo: can't contact portmapper")
OUTPUT ("rpcinfo: Kann den Portmapper nicht erreichen")
INPUT ("same rule name in multiple files")
OUTPUT ("Dieselbe Regel ist in mehreren Dateien enthalten")
INPUT ("short read while reading request key: %s")
OUTPUT ("Kurzer Read beim Lesen des Anforderungsschlüssels: %s")
INPUT ("short read while reading request: %s")
OUTPUT ("Kurzer Read beim Lesezugriff: %s")
INPUT ("short write in %s: %s")
OUTPUT ("Kurzer Write in »%s«: %s")
INPUT ("socket: protocol failure in circuit setup\n")
OUTPUT ("socket: Protokollfehler im Verbindungsaufbau\n")
INPUT ("sorting order `forward' and `backward' are mutually exclusive")
OUTPUT ("Die Anweisungen »forward« und »backward« schließen sich aus")
INPUT ("specification of sorting weight for collation symbol does not make sense")
OUTPUT ("Die Angabe eines Sortiergewichtes für ein Sortiersymbol ist nicht sinnvoll")
INPUT ("standard input")
OUTPUT ("Standardeingabe")
INPUT ("standard output")
OUTPUT ("Standardausgabe")
INPUT ("starting date is illegal in string %d in `era' field in category `%s'")
OUTPUT ("Das Start-Datum in der Zeichenkette %d im »era«-Feld der Kategorie »%s« ist ungültig")
INPUT ("starting year greater than ending year")
OUTPUT ("Das Start-Jahr ist größer als das Ende-Jahr")
INPUT ("starting year too high to be represented")
OUTPUT ("Das Startjahr ist zu groß für die Darstellung")
INPUT ("starting year too low to be represented")
OUTPUT ("Das Startjahr ist zu klein für die Darstellung")
INPUT ("stopping date is illegal in string %d in `era' field in category `%s'")
OUTPUT ("Das Ende-Datum in der Zeichenkette %d im »era«-Feld in der Kategorie »%s« ist ungültig")
INPUT ("svc_run: - select failed")
OUTPUT ("svc_run - »select« ist fehlgeschlagen")
INPUT ("svc_tcp.c - cannot getsockname or listen")
OUTPUT ("svc_tcp.c - »getsockname« oder »listen« nicht möglich")
INPUT ("svc_tcp.c - tcp socket creation problem")
OUTPUT ("svc_tcp.c - Problem bei der Erstellung des TCP-Sockets")
INPUT ("svc_tcp: makefd_xprt: out of memory\n")
OUTPUT ("svc_tcp: makefd_xprt: Hauptspeicher erschöpft\n")
INPUT ("svc_unix.c - AF_UNIX socket creation problem")
OUTPUT ("svc_unix.c - Problem bei der Erstellung des AF_UNIX-Sockets")
INPUT ("svc_unix.c - cannot getsockname or listen")
OUTPUT ("svc_unix.c - »getsockname« oder »listen« nicht möglich")
INPUT ("svc_unix: makefd_xprt: out of memory\n")
OUTPUT ("svc_unix: makefd_xprt: Hauptspeicher erschöpft\n")
INPUT ("svctcp_create: out of memory\n")
OUTPUT ("svctcp_create: Hauptspeicher erschöpft\n")
INPUT ("svcudp_create - cannot getsockname")
OUTPUT ("svcudp_create - »getsockname« fehlgeschlagen")
INPUT ("svcudp_create: out of memory\n")
OUTPUT ("svcudp_create: Hauptspeicher erschöpft\n")
INPUT ("svcudp_create: socket creation problem")
OUTPUT ("svcudp_create: Problem bei der Erstellung des Sockets")
INPUT ("svcunix_create: out of memory\n")
OUTPUT ("svcunix_create: Hauptspeicher erschöpft\n")
INPUT ("symbol for multicharacter collating element `%.*s' duplicates element definition")
OUTPUT ("Das Symbol für das Mehr-Zeichen Sortierelement »%.*s« wiederholt die Elementdefinition")
INPUT ("symbol for multicharacter collating element `%.*s' duplicates other symbol definition")
OUTPUT ("Das Symbol für das 'multicharacter' Sortierelement »%.*s« wiederholt eine andere Symboldefinition")
INPUT ("symbol for multicharacter collating element `%.*s' duplicates symbol definition")
OUTPUT ("Das Symbol für das 'multicharacter' Sortierelement »%.*s« wiederholt eine Symboldefinition")
INPUT ("symbol for multicharacter collating element `%.*s' duplicates symbolic name in charset")
OUTPUT ("Das Symbol für das 'multicharacter' Sortierelement »%.*s« kollidiert mit einem symbolischen Namen in der Zeichensatzbeschreibung")
INPUT ("syntax error in %s definition: %s")
OUTPUT ("Syntaxfehler in der »%s«-Definition: %s")
INPUT ("syntax error in `order_start' directive")
OUTPUT ("Syntaxfehler in der »order_start«-Anweisung")
INPUT ("syntax error in character class definition")
OUTPUT ("Syntaxfehler in der Zeichenklassendefinition")
INPUT ("syntax error in character conversion definition")
OUTPUT ("Syntaxfehler in der Zeichensatzumwandlungsdefinition")
INPUT ("syntax error in collating order definition")
OUTPUT ("Syntaxfehler in der Definition der Sortierreihenfolge")
INPUT ("syntax error in collation definition")
OUTPUT ("Syntaxfehler in der Definition der Sortierung")
INPUT ("syntax error in definition of LC_CTYPE category")
OUTPUT ("Syntaxfehler in der Definition der »LC_CTYPE«-Kategorie")
INPUT ("syntax error in definition of new character class")
OUTPUT ("Syntaxfehler in der Definition einer neuen Zeichenklasse")
INPUT ("syntax error in definition of new character map")
OUTPUT ("Syntaxfehler in der Definition eines neuen Zeichensatzes")
INPUT ("syntax error in message locale definition")
OUTPUT ("Syntaxfehler in der Lokale-Definitionsdatei, Abschnitt »message«")
INPUT ("syntax error in monetary locale definition")
OUTPUT ("Syntaxfehler in der Lokale-Definitionsdatei, Abschnitt »monetary«")
INPUT ("syntax error in numeric locale definition")
OUTPUT ("Syntaxfehler in der Lokale-Definitionsdatei, Abschnitt »numeric«")
INPUT ("syntax error in order specification")
OUTPUT ("Syntaxfehler in der Lokale-Definitionsdatei, Abschnitt »order«")
INPUT ("syntax error in prolog: %s")
OUTPUT ("Syntaxfehler im Prolog: %s")
INPUT ("syntax error in repertoire map definition: %s")
OUTPUT ("Syntaxfehler in der »repertoire« Map-Definition: %s")
INPUT ("syntax error in time locale definition")
OUTPUT ("Syntaxfehler in der Lokale-Definition zur Zeit (Abschnitt »time«)")
INPUT ("syntax error: not inside a locale definition section")
OUTPUT ("Syntaxfehler: nicht in einem Abschnitt der Lokale-Definition")
INPUT ("target encoding not specified using `-t'")
OUTPUT ("Die Zielkodierung ist nicht mittels »-t« angegeben")
INPUT ("this is the first definition")
OUTPUT ("Dies ist die erste Definition")
INPUT ("time before zero")
OUTPUT ("Zeit vor Null")
INPUT ("time overflow")
OUTPUT ("Überlauf der Zeit")
INPUT ("too few bytes in character encoding")
OUTPUT ("Zu wenige Bytes in der Zeichenkodierung")
INPUT ("too many bytes in character encoding")
OUTPUT ("Zu viele Bytes in der Zeichenkodierung")
INPUT ("too many character classes defined")
OUTPUT ("Zu viele Zeichenklassen definiert")
INPUT ("too many leap seconds")
OUTPUT ("Zu viele Schaltsekunden")
INPUT ("too many local time types")
OUTPUT ("Zu viele Ortszeittypen")
INPUT ("too many transitions?!")
OUTPUT ("Zu viele Übergänge?!")
INPUT ("too many weights")
OUTPUT ("Zu viele Sortiergewichte")
INPUT ("too many, or too long, time zone abbreviations")
OUTPUT ("Zu viele oder zu lange Abkürzungen für Zeitzonen")
INPUT ("trailing garbage at end of line")
OUTPUT ("Am Zeilenende sind unsinnige Einträge")
INPUT ("trouble replying to prog %d\n")
OUTPUT ("Schwierigkeiten bei der Antwort an das Programm %d\n")
INPUT ("two lines in a row containing `...' are not allowed")
OUTPUT ("Zwei aufeinanderfolgende Zeilen mit »...« sind nicht erlaubt")
INPUT ("typed single year")
OUTPUT ("Ein einzelnes Jahr angegeben")
INPUT ("unable to allocate buffer for input")
OUTPUT ("Fehler beim Allozieren des Puffers für die Eingabe")
INPUT ("unable to free arguments")
OUTPUT ("Fehler beim Freigeben des Speichers für die Argumente")
INPUT ("undefined")
OUTPUT ("nicht definiert")
INPUT ("unknown character `%s'")
OUTPUT ("unbekanntes Zeichen »%s«")
INPUT ("unknown character in field `%s' of category `%s'")
OUTPUT ("Ungültiges Zeichen im Feld »%s« in der Kategorie »%s«")
INPUT ("unknown collation directive")
OUTPUT ("unbekannte »collation«-Anweisung")
INPUT ("unknown directive `%s': line ignored")
OUTPUT ("unbekannte Anweisung »%s«: Die Zeile wurde ignoriert")
INPUT ("unknown iconv() error %d")
OUTPUT ("unbekannter iconv()-Fehler %d")
INPUT ("unknown set `%s'")
OUTPUT ("Unbekanntes Set »%s«")
INPUT ("unknown symbol `%.*s': line ignored")
OUTPUT ("Unbekanntes Symbol »%.*s«: Die Zeile wurde ignoriert")
INPUT ("unruly zone")
OUTPUT ("Zeitzone ohne Regeln")
INPUT ("unterminated message")
OUTPUT ("Die Nachricht ist nicht abgeschlossen")
INPUT ("unterminated string")
OUTPUT ("Zeichenkette wird nicht beendet")
INPUT ("unterminated string constant")
OUTPUT ("Zeichenkette wird nicht beendet")
INPUT ("unterminated symbolic name")
OUTPUT ("Der symbolische Name wird nicht beendet")
INPUT ("unterminated weight name")
OUTPUT ("Der Name des Sortiergewichtes wird nicht beendet")
INPUT ("upper limit in range is not smaller then lower limit")
OUTPUT ("Das obere Ende des Intervalls ist nicht kleiner als das untere Ende")
INPUT ("usage: %s infile\n")
OUTPUT ("Syntax: %s Eingabedatei\n")
INPUT ("use of 2/29 in non leap-year")
OUTPUT ("Der 29. Februar wurde in einem Jahr verwendet, das kein Schaltjahr ist")
INPUT ("value for %s must be an integer")
OUTPUT ("Der Wert für »%s« muß eine Ganzzahl sein")
INPUT ("value for <%s> must lie between 1 and 4")
OUTPUT ("Der Wert für »<%s>« muß zwischen eins und vier liegen")
INPUT ("value for field `%s' in category `%s' must not be the empty string")
OUTPUT ("Der Eintrag für das Feld »%s« in der Kategorie »%s« darf nicht leer sein")
INPUT ("value of <mb_cur_max> must be greater than the value of <mb_cur_min>")
OUTPUT ("Der Wert von »<mb_cur_max>« muß größer als der Wert von »<mb_cur_min>« sein")
INPUT ("value of field `int_curr_symbol' in category `LC_MONETARY' does not correspond to a valid name in ISO 4217")
OUTPUT ("Der Wert im Feld »int_curr_symbol« in der Kategorie »LC_MONETARY« gehört nicht zu einem gültigen Namen in ISO-4217")
INPUT ("value of field `int_curr_symbol' in category `LC_MONETARY' has wrong length")
OUTPUT ("Der Wert im Feld »int_curr_symbol« in der Kategorie »LC_MONETARY« hat die falsche Länge")
INPUT ("values for field `%s' in category `%s' must be smaller than 127")
OUTPUT ("Der Wert für den Eintrag »%s« in der Kategorie »%s« muß kleiner als 127 sein.")
INPUT ("warning: ")
OUTPUT ("Warnung: ")
INPUT ("while accepting connection: %s")
OUTPUT ("Beim Annehmen der Verbindung: %s")
INPUT ("while allocating cache entry")
OUTPUT ("Beim Anfordern eines Cache-Eintrages")
INPUT ("while allocating hash table entry")
OUTPUT ("Fehler beim Allozieren des Eintrages in die Hash-Tabelle")
INPUT ("while allocating key copy")
OUTPUT ("Beim Anfordern einer Schlüssel-Kopie")
INPUT ("while opening old catalog file")
OUTPUT ("beim Öffnen der alten Katalogdatei")
INPUT ("while preparing output")
OUTPUT ("beim Aufbereiten der Ausgabe")
INPUT ("while reading database")
OUTPUT ("beim Lesen der Datenbank")
INPUT ("while stat'ing profiling data file")
OUTPUT ("beim Holen des Dateistatus der Datei mit den Profiling-Daten")
INPUT ("while writing database file")
OUTPUT ("beim Schreiben der Datenbankdatei")
INPUT ("write incomplete")
OUTPUT ("Der 'Write' wurde nur unvollständig ausgeführt")
INPUT ("writeable by other than owner")
OUTPUT ("ist auch für andere Benutzer als den Dateieigentümer beschreibbar")
INPUT ("wrong number of arguments")
OUTPUT ("Falsche Anzahl an Argumenten")
INPUT ("wrong number of fields on Leap line")
OUTPUT ("Falsche Anzahl an Feldern in der Leap-Zeile")
INPUT ("wrong number of fields on Link line")
OUTPUT ("Falsche Anzahl der Felder in der Link-Zeile")
INPUT ("wrong number of fields on Rule line")
OUTPUT ("Falsche Anzahl der Felder in der Rule-Zeile")
INPUT ("wrong number of fields on Zone continuation line")
OUTPUT ("Falsche Anzahl der Felder in der Zeitzonen-Fortsetzungszeile")
INPUT ("wrong number of fields on Zone line")
OUTPUT ("Falsche Anzahl an Feldern in der Zone-Zeile")
INPUT ("xdr_reference: out of memory\n")
OUTPUT ("xdr_reference: Hauptspeicher erschöpft\n")
INPUT ("xdrrec_create: out of memory\n")
OUTPUT ("xdrrec_create: Hauptspeicher erschöpft\n")
INPUT ("yp_update: cannot convert host to netname\n")
OUTPUT ("yp_update: Kann den Rechnername nicht in einen Netzname umwandeln\n")
INPUT ("yp_update: cannot get server address\n")
OUTPUT ("yp_update: Kann die Adresse des Servers nicht finden\n")
